% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{book}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Introduction to Computational and Data Sciences},
  pdfauthor={James K. Glasbrenner; Ajay Kulkarni; Dominic White},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\usepackage{amsthm}
\makeatletter
\def\thm@space@setup{%
  \thm@preskip=8pt plus 2pt minus 4pt
  \thm@postskip=\thm@preskip
}
\makeatother
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[]{natbib}
\bibliographystyle{plainnat}
\nocite{downey14_think_stats, R-bookdown, R-dplyr, R-ggplot2, R-infer, R-kableExtra, R-knitr, R-readr, R-rmarkdown, R-tinytex}

\title{Introduction to Computational and Data Sciences}
\author{James K. Glasbrenner \and Ajay Kulkarni \and Dominic White}
\date{2022-06-27}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{frontmatter}{%
\chapter*{Frontmatter}\label{frontmatter}}
\addcontentsline{toc}{chapter}{Frontmatter}

Supplemental Textbook for CDS 101: Introduction to Computational and Data Sciences at George Mason University.

{Introduction to Computational and Data Sciences} is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.

\hypertarget{r-session-information}{%
\section*{R session information}\label{r-session-information}}
\addcontentsline{toc}{section}{R session information}

The R session information when compiling this book is shown below:

\begin{verbatim}
## R version 4.1.2 (2021-11-01)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Pop!_OS 22.04 LTS
## 
## Locale:
##   LC_CTYPE=en_US.UTF-8      
##   LC_NUMERIC=C              
##   LC_TIME=en_US.UTF-8       
##   LC_COLLATE=en_US.UTF-8    
##   LC_MONETARY=en_US.UTF-8   
##   LC_MESSAGES=en_US.UTF-8   
##   LC_PAPER=en_US.UTF-8      
##   LC_NAME=C                 
##   LC_ADDRESS=C              
##   LC_TELEPHONE=C            
##   LC_MEASUREMENT=en_US.UTF-8
##   LC_IDENTIFICATION=C       
## 
## Package version:
##   bookdown_0.26    dplyr_1.0.9      ggplot2_3.3.6   
##   infer_1.0.2      kableExtra_1.3.4 knitr_1.39      
##   readr_2.1.2      rmarkdown_2.14.1 tinytex_0.39    
## 
## Pandoc version: 2.17.1.1
## 
## LaTeX version used: 
##   TeX Live 2022 (TinyTeX) with tlmgr 2022-04-18
\end{verbatim}

\hypertarget{part-toolbox}{%
\part{Toolbox}\label{part-toolbox}}

\hypertarget{toolbox-introduction}{%
\chapter{Introduction}\label{toolbox-introduction}}

The following chapters will help you become familiar with the software and online platforms that will be used during the course.

\hypertarget{slack}{%
\chapter{Slack}\label{slack}}

\hypertarget{getting-started}{%
\section{Getting started}\label{getting-started}}

\hypertarget{creating-a-slack-account}{%
\subsection{Creating a Slack account}\label{creating-a-slack-account}}

After submitting a signed FERPA waiver on Blackboard, you will be invited to our Slack workspace via email. Please make sure to register with your \emph{\citet{masonlive.gmu.edu}} email address.

\begin{itemize}
\tightlist
\item
  You will not be able to join Slack until your instructor has approved your uploaded FERPA waiver and sent you the invitation email.
\item
  You will use the same Slack workspace for CDS 101 and CDS 102 (if you are registered for both classes).

  \begin{itemize}
  \tightlist
  \item
    You must upload a separate FERPA waiver to the Blackboard section for each class.
  \item
    You will receive a single invite to the shared Slack workspace, and each class's instructor will then add you to the appropriate channels for your section.
  \end{itemize}
\end{itemize}

You can access Slack through a web browser, mobile app, or desktop app. Once you have joined, you can customize your account by:

\begin{itemize}
\tightlist
\item
  changing your username (please stick to either your NetID or \emph{FirstName LastName} so that we know who you are!)
\item
  uploading a profile picture. This is not required, but will help us get to know you better over the course of this semester. \emph{However}, if you do change your picture, \emph{this should be a picture of you}, not of a cartoon, political figure, offensive or provocative imagery, etc.
\end{itemize}

\hypertarget{slack-policies}{%
\subsection{Slack policies}\label{slack-policies}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Please be respectful and polite with all communication on Slack.
\item
  Follow the guidelines for asking questions.
\item
  Do not post answers or solutions (see our guidelines for helping out other students).
\end{enumerate}

\hypertarget{how-to-use-slack}{%
\section{How to use Slack}\label{how-to-use-slack}}

Slack is a messaging tool (very similar to Discord, Microsoft Teams, etc.). There will be two main ways that you use Slack to communicate with instructors and other students:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Public messages in shared \emph{channels}
\item
  Private messages to 1 or more recipients using \emph{direct messages}
\end{enumerate}

\hypertarget{channels}{%
\subsection{Channels}\label{channels}}

You and other students from the your section (and other sections) will be assigned to shared channels.

Here are some important channels in our Slack workspace and their uses:

\begin{itemize}
\item
  \emph{\#101-section-001}: This is an example of a private channel for students in CDS 101 Section 001. You will be assigned to similar channel for your section of CDS 101 and/or 102. Your instructor will use it for communicating information relevant to your class only (and you may also use it if you have a reason to communicate with all other students in your section).
\item
  \emph{\#101-module01-intro}: This is an example of a public channel for the 1st module of CDS 101. There will be a separate channel for each CDS 101 module (as well as a separate channel for each CDS 102 lab). You should use this channel to ask questions about any of the materials/quizzes/assignments for that module/lab.
\item
  \emph{\#announcements}: This channel will be used by instructos and STARS for course-wide announcements, e.g.~office hour reminders.
\item
  \emph{\#rstudio-github-help}: A channel for general help questions about RStudio or GitHub rather than a particular module or lab (e.g.~if you can't login to RStudio),
\item
  \emph{\#random}: A channel for any other messages that would be off-topic in the other dedicated channels (e.g.~general questions about this course, questions about other CDS courses, speculation about the Patriot's chances in the NCAA, etc.)
\end{itemize}

To prevent plagiarism, please do not post extensive or working code for any of the exercises in channels (use a direct message instead).

\hypertarget{direct-messages}{%
\subsection{Direct messages}\label{direct-messages}}

You can send a private message to one or more people as a \emph{Direct Message}.

To do this, scroll down to the ``Direct Messages'' section of the left-hand menu in Slack, and click the + symbol. Then search for the users you want to message.

If you want to include code in a question, please send it in a Direct Message to your instructor and one of the STARS for your section (i.e.~use a single DM with 2 recipients so that we are all in the same message thread). However, if your question doesn't include an answer that other students could copy then it is preferable to post in in the shared channel for that Module/Lab, as then any other student with the same question can see how we were able to help you.

\hypertarget{asking-questions}{%
\subsection{How to ask (good) questions on Slack}\label{asking-questions}}

Good questions:

\begin{itemize}
\tightlist
\item
  Post as much information about your problem as possible, so that we can help you as quickly as possible.
\item
  Show that you have made a good faith effort to understand the question and answer it yourself before getting stuck.
\item
  Don't post an entire code chunk or multiple lines of working code in public channels (to prevent plagiarism). Use a direct message to your instructor + one of the STARS instead.
\end{itemize}

Let's go through some examples of bad questions to illustrate these principles:

\begin{itemize}
\item
  \begin{quote}
  Help, I'm getting an error on Exercise 4.
  \end{quote}

  The problem with this question is that there are a huge range of errors that you could be getting - so our question to you will be ``What error message?'' This could significantly slow down our communication since Slack is an asynchronous tool.

  Instead, include as much relevant information as you can to help us fix the problem. It is helpful if you can copy the entire error message from RStudio, if you have one, as well as telling us which Exercise you were working on when this happened.

  For example,

  \begin{quote}
  I'm getting this error message on Exercise 4:

  \texttt{Error:\ object\ \textquotesingle{}height\textquotesingle{}\ not\ found.}
  \end{quote}
\item
  \begin{quote}
  I don't understand Exercise 3.
  \end{quote}

  of

  \begin{quote}
  Can somebody tell me the answer to Exercise 2?
  \end{quote}

  We want to see that you have made an effort to answer each exercise. To do this we need to know where you are in your understanding of each exercise.

  And while we will not just ``tell you the answer'', we will help you until you are able to figure out the answer yourself. However, to do this we again need to know what about that question is giving you trouble.

  The answers to almost every question can be found by going back through the interactive tutorials/lecture videos/readings/assignment instructions. Therefore your first strategy when stuck should be to go back through these resources to find the answer.

  For example, here is how you might ask this question better:

  \begin{quote}
  In Exercise 3, I am not sure how to procede with Part ii where it asks ``Sort the dataframe in ascending order using the \texttt{name} column''. I've looked back through the interactive tutorial for a function to sort a dataframe, but I haven't found one.
  \end{quote}
\item
  \begin{quote}
  This code chunk is giving me an error:

\begin{verbatim}
some code
that is an
entire code chunk
(even if it currently isn't working)
\end{verbatim}
  \end{quote}

  In general you should avoid posting large amounts of code in a shared channel because:

  \begin{enumerate}
  \def\labelenumi{\arabic{enumi}.}
  \tightlist
  \item
    Another student might just copy your code rather than solving the problem themselves
  \item
    We check for similarities between answers, and so you might get into trouble because another student copied code you posted on Slack
  \end{enumerate}

  You can circumvent these issues by posting just the error message and not the code, or if you think the code is necessary to help us answer your question, please send it as a Direct Message to an instructor + STAR rather than a message in a public channel.

  It is fine to post small amounts of code in the public channels, e.g.~one line from a multi-line code chunk, or part of a line.

  A good rule of thumb is that whatever is posted in public channels should help other students with a similar problem figure out how to solve it. However they should not just be able to copy what you have posted and recycle it in their own assignment without understanding it.
\end{itemize}

\hypertarget{github}{%
\chapter{GitHub}\label{github}}

\hypertarget{getting-started-1}{%
\section{Getting started}\label{getting-started-1}}

\hypertarget{github-signup}{%
\subsection{Account sign-up}\label{github-signup}}

To create an account on GitHub, begin by launching your web browser and navigate to \url{https://github.com/}.

\begin{center}\includegraphics[width=1\linewidth]{img/signup_step_1} \end{center}

In the signup form, enter your \textbf{your Mason \texttt{@gmu.edu} or \texttt{@masonlive.gmu.edu} email address}, a username, and a password, and then click on the ``sign up for GitHub'' button

\begin{center}\includegraphics[width=1\linewidth]{img/signup_step_2} \end{center}

After creating the account on GitHub, you will see a new page containing details about plans for repositories.
Keep the default options and click on the ``Continue'' button.

\begin{center}\includegraphics[width=1\linewidth]{img/signup_step_3} \end{center}

The next page asks you to provide information about your programming experience and other details.
This is optional.
To skip this step, click on the ``skip this step'' link.
Otherwise, once you are done entering the information, click the ``Submit'' button.

\begin{center}\includegraphics[width=1\linewidth]{img/signup_step_4} \end{center}

Your Github account is now created and you will be greeted with the welcome page.
You will also receive an email about account verification.
Please click on the link in the email to verify your account.

\begin{center}\includegraphics[width=1\linewidth]{img/signup_step_5} \end{center}

\hypertarget{navigating-the-github-site}{%
\section{Navigating the GitHub site}\label{navigating-the-github-site}}

For your convenience, the course website contains links taking you directly to course content stored on GitHub.
However, you may prefer to access your existing content by navigating the GitHub site itself, so let's take a short tour of the GitHub interface.

\hypertarget{github-navigation-main-dashboard}{%
\subsection{Main dashboard}\label{github-navigation-main-dashboard}}

When you will login into GitHub for the first time you will see the main dashboard for the website.

\begin{center}\includegraphics[width=1\linewidth]{img/dashboard_first_icons} \end{center}

At the top of the dashboard there are several buttons, boxes, and icons that you can click in order to navigate the site.
Starting from the left,

\begin{itemize}
\item
  \textbf{GitHub icon}: This is similar to the ``Home'' or ``Main'' buttons found on other websites.
  Clicking this icon brings you back to your currently active dashboard, which is what we're already viewing.
\item
  \textbf{Search bar}: Used to look for content on the GitHub site, such as repositories and user accounts, just click it and start typing.
\item
  \textbf{Pull requests}, \textbf{Issues}, \textbf{Marketplace}, and \textbf{Explore}: Of these links, the only one you might use for the course is ``Pull requests'', however we'll save the discussion about Pull requests for another time.
\item
  \textbf{Bell icon}: This displays your account notifications, such as when someone tags your username.
\item
  \textbf{Plus icon}: Used for creating content, such as creating a new repository.
\end{itemize}

The last icon on the right is your profile picture, and clicking it opens up another menu containing some additional links.

\begin{center}\includegraphics[width=1\linewidth]{img/navigating_step_3_2} \end{center}

From this menu you can reach your profile, account settings, the help section, and a couple other of other pages.
Let's take a quick look to see what the profile and settings pages look like.

\hypertarget{profile-page}{%
\subsection{Profile page}\label{profile-page}}

Clicking \textbf{Your profile} will take you to your account's profile page.

\begin{center}\includegraphics[width=1\linewidth]{img/repository_step_8} \end{center}

Since you most likely have a new account, there won't be much here right now.
If you click the \textbf{Repositories} tab at the top of your profile, it will display a list of repositories associated with your account, \emph{however keep in mind that it will not have any content you work on for the class}.
This is because the repositories you create for the class assignments are created under the class organization rather than associated with you.
This is important to keep in mind when you are looking for your files - see below for how to find your class assignment repositories.

\hypertarget{settings}{%
\subsection{Settings}\label{settings}}

Clicking \textbf{Settings} takes you to the account settings page where you can inspect and update your account settings.
Use the menu on the left to choose the setting you would like to change.

\begin{center}\includegraphics[width=219px]{img/github_account_settings_menu} \end{center}

For now you may want to upload a profile picture or add a short bio under the \textbf{Profile} setting.
You can also change how the site sends you email updates and notification alerts under the \textbf{Emails} and \textbf{Notifications} settings.

\hypertarget{class-organization-page}{%
\subsection{Class organization page}\label{class-organization-page}}

Returning to the main dashboard, after you've complete a few of the assignments for the class, your dashboard will begin to look more like this.

\begin{center}\includegraphics[width=1\linewidth]{img/dashboard_dropdown_menu} \end{center}

As we learned while looking at the profile page, your classwork will not be visible there.
Instead, you will need to navigate to the class organization in order to find your files for the class, so let's do that now.

Your section's organization (for CDS 101) will be at a URL like this:

\begin{itemize}
\tightlist
\item
  \url{https://github.com/mason-sp20-cds101-001}
\item
  \url{https://github.com/mason-sp20-cds101-002}
\item
  \url{https://github.com/mason-sp20-cds101-dl1}
\item
  \url{https://github.com/mason-sp20-cds101-dl2}
\end{itemize}

In these examples, \texttt{sp20} stands for the Spring 2020 semester, and the last three digits are the number of your section.

When you navigate to your appropriate class organization page, you should see a page similar to this:

\begin{center}\includegraphics[width=1\linewidth]{img/dashboard_course_organization} \end{center}

The dashboard is similar to the dashboard we saw earlier, but it will only contain content associated with the class.
On the left you will see a list of some of your class repositories, which you can filter by typing in the \emph{Find a repository\ldots{}} search box.
If you don't see any repositories there, don't worry, we will get around to creating them soon enough!

To see a full list of your class repositories, similar to the repositories tab on your profile page, click the \textbf{View organization} button on the upper right of the page.

\begin{center}\includegraphics[width=1\linewidth]{img/course_organization_repo_list} \end{center}

Here you should be able to find all of the repositories that you've used during the class.

{Keep in mind}

If you click the \textbf{GitHub icon} while you are accessing content in the class organization, \emph{it will bring you back to the class organization dashboard, not the \protect\hyperlink{github-navigation-main-dashboard}{main dashboard} we saw earlier}.
To get back to the main dashboard, click the gray icon with the class organization name and then click your username in the dropdown menu.

\hypertarget{repositories}{%
\section{Repositories}\label{repositories}}

When you access a repository on GitHub, the page will look similar to the screenshot below,

\begin{center}\includegraphics[width=1\linewidth]{img/demo_repo_tabs_and_buttons} \end{center}

The page contains a lot of information about the repository along with multiple tabs and buttons, which can be a bit overwhelming at first.
As it turns out, we will not need to use many of these tabs or buttons during the class, so instead let's focus on the most important ones, which have been highlighted in the red and blue rectangles.

\begin{itemize}
\tightlist
\item
  Red

  \begin{itemize}
  \tightlist
  \item
    \textbf{Code tab:} Clicking this brings you back to the main repository page, which is what is displayed in the above screenshot
  \item
    \textbf{Commit tab:} takes you to the commit history for the repository, which are the series of ``snapshots'' that you create using the \texttt{git} tool in RStudio
  \end{itemize}
\item
  Blue

  \begin{itemize}
  \tightlist
  \item
    \textbf{Dropdown branch menu:} use this to inspect a branch that is different from the default \textbf{master} branch
  \item
    \textbf{Clone or download button:} provides a link to use when obtaining a copy of a repository. For the class, you will do this by creating a new project in RStudio using the \emph{version control} option.
  \item
    \textbf{Pull requests tab:} generally used for code reviews and quality control when a user wants to contribute code to a repository. For the class, pull requests will be used to submit your work so that the instructor is able to leave line-by-line comments about your code.
  \end{itemize}
\end{itemize}

Below the tabs and button is a list of files stored in the repository,

\begin{center}\includegraphics[width=1\linewidth]{img/demo_repo_files_list} \end{center}

Each repository will have different files.
Clicking a file's name will bring you to another page that shows a preview of the file contents.
The descriptions in the middle of the file list show the most recent commit message for each file and the timespan on the right shows how recently the file was last updated.

The above file list also shows you what you'll see in a folder after you first obtain a copy of the repository.
In that way, each repository can be thought of as a folder containing files,

\begin{center}\includegraphics[width=1\linewidth]{img/repo_files_windows_folder} \end{center}

The advantage of this approach is that each repository you create is isolated and separate, which helps to reduce certain kinds of coding errors.

Below the repository file list is a rendered version of the \texttt{README.md} file,

\begin{center}\includegraphics[width=1\linewidth]{img/demo_repo_readme_box} \end{center}

The \texttt{README.md} file describes the contents of the repository and can be used as a form of documentation.
It is a good idea to look at the \texttt{README.md} file of any repository you visit on GitHub to see if it gives examples or quick instructions on how to set up and use the files.

\hypertarget{additional-topics}{%
\section{Additional topics}\label{additional-topics}}

\hypertarget{how-to-create-a-repository}{%
\subsection{How to create a repository}\label{how-to-create-a-repository}}

We saw in the last tutorial that after creating an account on GitHub, there are three ways to create a repository. The most common method of creating a repository is to click on ``+'' sign and then click on ``New repository'' option.

\begin{center}\includegraphics[width=1\linewidth]{img/repository_step_1} \end{center}

After clicking on ``New repository'' you will go to a new screen where you need to give a repository name. You will also find two options to either keep repository as public or private. In the end, there will be another option to initialize the repository with Readme.md file.

\begin{center}\includegraphics[width=1\linewidth]{img/repository_step_2} \end{center}

GitHub doesn't allow to create a repository without a name. Thus, it is mandatory to give a name to the repository. After providing all the details and selecting appropriate options click on ``Create repository'' button.

\begin{center}\includegraphics[width=1\linewidth]{img/repository_step_3} \end{center}

In this way, the repository will be successfully created. If you have ticked on initializing the repository with Readme.md file, then you will find the file in the repository. You can easily edit Readme.md file by clicking on the file.

\begin{center}\includegraphics[width=1\linewidth]{img/repository_step_4} \end{center}

After clicking Readme.md file if you want to add any content in that file then click on the pencil symbol. Click on ``Commit'' button after making changes in the file.

\begin{center}\includegraphics[width=1\linewidth]{img/repository_step_5} \end{center}

\hypertarget{how-to-import-a-repository}{%
\subsection{How to import a repository}\label{how-to-import-a-repository}}

To import a repository from another account click on the ``+'' sign and then click on ``Import repository'' option. After that, you need to provide a link of the other repository which you need to clone or import and the repository name to store it under on your GitHub account. After giving all the details click on ``Begin import'' button.

\begin{center}\includegraphics[width=1\linewidth]{img/repository_step_6} \end{center}

The import process will start, and you will get a notification after completion of the import process.

\begin{center}\includegraphics[width=1\linewidth]{img/repository_step_7} \end{center}

Finally, you will be able to see the imported repository in your GitHub account.

\begin{center}\includegraphics[width=1\linewidth]{img/repository_step_8} \end{center}

\hypertarget{rstudio-server}{%
\chapter{RStudio Server}\label{rstudio-server}}

\hypertarget{big-picture-overview-of-rstudio-server}{%
\section{Big picture overview of RStudio Server}\label{big-picture-overview-of-rstudio-server}}

\hypertarget{rstudio}{%
\subsection{RStudio}\label{rstudio}}

\begin{quote}
RStudio is an integrated development environment (IDE) for R. It includes a console, syntax-highlighting editor that supports direct code execution, as well as tools for plotting, history, debugging and workspace management. RStudio is available in open source and commercial editions and runs on the desktop (Windows, Mac, and Linux) or in a browser connected to RStudio Server or RStudio Server Pro (Debian/Ubuntu, RedHat/CentOS, and SUSE Linux). RStudio team also contributes code to many R packages like Shiny, tidyverse, rmarkdown, etc.
\end{quote}

\hypertarget{rstudio-server-1}{%
\subsection{RStudio Server}\label{rstudio-server-1}}

\begin{quote}
RStudio Server is a product of RStudio which can be accessed via web browser. You can access RStudio Server by authenticating on \url{https://rstudio.cos.gmu.edu}. Some of the essential features of RStudio Server are given below,
\end{quote}

\begin{quote}
\begin{itemize}
\tightlist
\item
  Integrates the tools you use with R into a single environment.
\item
  Includes powerful coding tools designed to enhance your productivity.
\item
  Enables rapid navigation to files and functions.
\item
  Make it easy to start new or find existing projects.
\item
  Provides integrated support for Git and Subversion.
\item
  Supports authoring HTML, PDF, Word Documents, and slideshows.
\item
  Supports interactive graphics with Shiny and ggvis.
\end{itemize}
\end{quote}

\hypertarget{reference}{%
\subsection{Reference}\label{reference}}

\begin{itemize}
\tightlist
\item
  \url{https://www.rstudio.com}
\end{itemize}

\hypertarget{a-guided-tour-of-rstudio-servers-default-interface}{%
\section{A guided tour of RStudio Server's default interface}\label{a-guided-tour-of-rstudio-servers-default-interface}}

In the last tutorial, we learned how to log in into RStudio Server. In this tutorial, we will understand the different options and their uses which RStudio Server provides.

\hypertarget{rstudio-server-sub-windows}{%
\subsection{RStudio Server sub-windows}\label{rstudio-server-sub-windows}}

When you log in into RStudio Server, you will be able to see four sub-windows.

\begin{itemize}
\item
  The upper left window is for creating, running, and saving scripts which consist of a series of commands that are to be executed in sequence. This window is also used for viewing data sets.
\item
  The window at the lower left is the Console, where individual commands are entered and executed, and the results are shown. When a script is run from the editor, the output will appear in the Console window.
\item
  The window at the upper right shows available data sets and objects when the Environment tab is selected, and it shows previously run commands when the History button is selected. It also provides you information about connections and Git.
\item
  The window at the lower right shows files and folders in the user's R folder in the image below, but this window also is used to display Help responses, and for displaying graphs and plots generated by R.
\end{itemize}

\begin{center}\includegraphics[width=1\linewidth]{img/tour_step_1} \end{center}

\hypertarget{file-tab}{%
\subsection{File tab}\label{file-tab}}

The RStudio File menu contains many of the standard functions of a File menu in any other software or program -- New File, Open File, Save, Print. You can also Knit a document by selecting Knit document option from file tab.

\begin{center}\includegraphics[width=1\linewidth]{img/tour_step_2} \end{center}

\hypertarget{edit-tab}{%
\subsection{Edit tab}\label{edit-tab}}

Using Edit menu users can perform Cut, Copy, Paste, Undo, and Redo. The Edit menu is also very helpful in locating code or commands previously used. Featuring Go to Line\ldots, Find\ldots, and Replace and Find, users can quickly edit or replace RStudio code. The Edit menu additionally has the command Clear Console which allows users to wipe the Console clean. Clear Console does not affect the Source, Environment/History, or Miscellaneous tabs.

\begin{center}\includegraphics[width=1\linewidth]{img/tour_step_3} \end{center}

\hypertarget{code-tab}{%
\subsection{Code tab}\label{code-tab}}

The Code menu has commands used for working with code. Similar to the Edit menu, Code offers Jump To\ldots{} for quick access to a specific code. Here you can rework the appearance of your code with Reformat Code, and where functions and variables may be removed with Extract Function and Extract Variable. The Code menu also provides commands for running the code with Run Selected Line(s), Re-Run Previous, and Run Region.

\begin{center}\includegraphics[width=1\linewidth]{img/tour_step_4} \end{center}

\hypertarget{view-tab}{%
\subsection{View tab}\label{view-tab}}

The View menu is focused on how the user sees their RStudio workspace. This menu allows you to choose which tab you want to view, as well as where the mouse should be focused. Panes focus on zoom abilities of RStudio and enable users to zoom in on a specific tab.

\begin{center}\includegraphics[width=1\linewidth]{img/tour_step_5} \end{center}

\hypertarget{plots-tab}{%
\subsection{Plots tab}\label{plots-tab}}

The Plots menu works specifically with plots that you have made in RStudio. This menu allows you to quickly switch between plots and zoom on the plot to enhance clarity. This is where you can choose to save your plot as either an image or a PDF, as well as where you may delete unwanted plots with Remove Plot\ldots.

\begin{center}\includegraphics[width=1\linewidth]{img/tour_step_6} \end{center}

\hypertarget{session-tab}{%
\subsection{Session tab}\label{session-tab}}

The Session menu allows users to open a New Session\ldots{} and Quit Session\ldots. Here you may also Terminate R\ldots{} if you are finished with using RStudio, or Restart R if an update needs to occur or the program needs to be refreshed.

\begin{center}\includegraphics[width=1\linewidth]{img/tour_step_7} \end{center}

\hypertarget{build-tab}{%
\subsection{Build tab}\label{build-tab}}

The Build menu features only one command: Configure Build Tools. Build Tools may only be configured inside of an RStudio project and are a way to package and distribute R code.

\begin{center}\includegraphics[width=1\linewidth]{img/tour_step_8} \end{center}

\hypertarget{debug-tab}{%
\subsection{Debug tab}\label{debug-tab}}

The Debug menu is what ensures your code is working correctly. When there is an error in your code or commands, the Debug menu will point out the errors and allow you to decide if you wish to keep working with your RStudio code. You may choose how you wish to be notified of an error by using the option ``On Error''. If you need additional help fixing an error, select Debugging Help.

\begin{center}\includegraphics[width=1\linewidth]{img/tour_step_9} \end{center}

\hypertarget{proflie-tab}{%
\subsection{Proflie tab}\label{proflie-tab}}

The Profile menu allows users to understand better what exactly RStudio is doing. Profiling provides a graphical interface so that users may see what RStudio is working on in moments when you are waiting for output to appear. By profiling, users can learn what is slowing their code so that they may tweak parts to make the code run faster.

\begin{center}\includegraphics[width=1\linewidth]{img/tour_step_10} \end{center}

\hypertarget{tools-tab}{%
\subsection{Tools tab}\label{tools-tab}}

The Tools menu provides information on the current version of RStudio being run, as well as being the location where Packages and Addins may be installed. Tools also assist RStudio users with Keyboard Shortcuts and allow users to Modify Keyboard Shortcuts to cater to individual's needs and preferences.

\begin{center}\includegraphics[width=1\linewidth]{img/tour_step_11} \end{center}

\hypertarget{help-tab}{%
\subsection{Help tab}\label{help-tab}}

The Help menu provides information to assist users to maximize their RStudio proficiency. Direct links to RStudio Help are provided, as well as Cheatsheets made by RStudio professionals and a section on Diagnostics to allow the user to see what is occurring in RStudio.

\begin{center}\includegraphics[width=1\linewidth]{img/tour_step_12} \end{center}

\hypertarget{references}{%
\subsection{References}\label{references}}

\begin{itemize}
\tightlist
\item
  \url{http://sphweb.bumc.bu.edu/otlt/MPH-Modules/QuantCore/PH717-R-Basics/PH717-R-Basics3.html}
\item
  \url{https://wp.stolaf.edu/it/rstudio-menu-bar/}
\end{itemize}

\hypertarget{help-and-documentation-for-r-and-rstudio-server}{%
\section{Help and documentation for R and RStudio Server}\label{help-and-documentation-for-r-and-rstudio-server}}

The help and documentation for R and RStudio Server are readily available in RStudio Server. In RStudio Server if you click on Help tab, then you will get a menu for selecting an option.

\begin{center}\includegraphics[width=1\linewidth]{img/help_step_1} \end{center}

If you click on R Help then in the lower right window you will get all the help for R as well as for RStudio. You can also search for any topic using the search box.

\begin{center}\includegraphics[width=1\linewidth]{img/help_step_2} \end{center}

If you want specific documentation for RStudio, then you need to click on RStudio docs. It will open a new tab in your browser and provide you with all the documentation.

\begin{center}\includegraphics[width=1\linewidth]{img/help_step_3} \end{center}

R documentation is also available on \url{https://www.rdocumentation.org/} website. You can find information about packages, functions and different parameters on R documentation website.

\begin{center}\includegraphics[width=1\linewidth]{img/help_step_5} \end{center}

RStudio also provide cheatsheets for help. In help tab, if you click on Cheatsheets option, then you will get another menu of available cheatsheets in RStudio.

\begin{center}\includegraphics[width=1\linewidth]{img/help_step_4} \end{center}

You can also find more resources (for data science, RStudio, etc.,) on RStudio website. Please visit \url{https://www.rstudio.com/resources} for more resources.

\begin{center}\includegraphics[width=1\linewidth]{img/help_step_6} \end{center}

\textbf{If you have any questions or stuck at any point, then please contact your instructor for the help.}

\hypertarget{initial-set-up}{%
\section{Initial Set-up}\label{initial-set-up}}

\hypertarget{change-global-options}{%
\subsection{Change Global Options}\label{change-global-options}}

To change the settings for RStudio Server, click Tools \textgreater{} Global Options\ldots{} in the top menu bar. A pop-up menu will appear with many different options for you to change. You are free to explore all the different options on your own. For now, there are two things you should change:

\begin{itemize}
\item
  Uncheck the box next to \textbf{Restore .RData into workspace at startup}
\item
  Click the drop-down menu next to \textbf{Save workspace to .RData on exit} and change the setting to \emph{Never}
\end{itemize}

Click the \textbf{Apply} button on the lower-right of the pop-up window, followed by the \textbf{OK} button.

\hypertarget{create-a-personal-access-token-on-github}{%
\subsection{Create a Personal Access Token on GitHub}\label{create-a-personal-access-token-on-github}}

A personal access token is essentially a temporary password that you can create to use with your GitHub account instead of your main account. It is much more secure than using your main GitHub password when working on GitHub projects.

Login to your account at GitHub account and follow steps 1-9 \href{https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token}{here} under the section \emph{Creating a Token}.

A few notes:

\begin{itemize}
\tightlist
\item
  In step 7, give your token a long enough expiration so that it will last past the end of the semester.
\item
  In step 8, you only need to check the box that says \textbf{repo}.
\item
  In step 9, \textbf{make sure you store a copy of the token} that is generated for you (e.g.~copy-and-paste it into a text file). You will never be able to view this token again on GitHub, so if you lose it, you will need to create a new token by repeating steps 1-9 all over again\ldots{}
\end{itemize}

Once you have created the token, return to RStudio, and move onto the next section:

\hypertarget{configure-rstudio-for-use-with-git}{%
\subsection{Configure RStudio for use with Git}\label{configure-rstudio-for-use-with-git}}

Take a look in the bottom-left pane of RStudio. You should see a tab called \emph{Console} which is open by default, and another one called \emph{Terminal}. Switch to the \emph{Terminal} tab. (If you do not see a Terminal, create one from the top menu in RStudio by going to \emph{Tools \textgreater{} Terminal \textgreater{} New Terminal}.)

It may take a few seconds for the \emph{Terminal} to load, but once it has done so you will see a line that ends with a dollar symbol \texttt{\$} and a flashing black cursor.

Copy-and-paste the following command into the \emph{Terminal} and then press \texttt{Enter} to run it:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{git}\NormalTok{ config }\AttributeTok{{-}{-}global}\NormalTok{ credential.helper store}
\end{Highlighting}
\end{Shaded}

Note that:

\begin{itemize}
\item
  You will not see any response in the \emph{Terminal} if the line runs successfully. However you can check if it was successful by running this line \texttt{git\ config\ credential.helper} - you should get the response \texttt{store}.
\item
  To paste copied text into the \emph{Terminal} with a keyboard shortcut, use Ctrl+Shift+v on your keyboard instead of just Ctrl+v (and if you are using a Mac, use the Cmd key instead of Ctrl).
\end{itemize}

Next we need to run two more lines in the \emph{Terminal}:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{git}\NormalTok{ config }\AttributeTok{{-}{-}global}\NormalTok{ user.name }\StringTok{"FirstName LastName"}
\FunctionTok{git}\NormalTok{ config }\AttributeTok{{-}{-}global}\NormalTok{ user.email }\StringTok{"netID@gmu.edu"}
\end{Highlighting}
\end{Shaded}

You should obviously replace the values inside the quotation marks with your name on the first line, and your GMU email address on the second line (which should match the email address you used to sign up for your GitHub account).

Next, switch back to the \emph{Console} tab of the bottom left pane (next to the \emph{Terminal} tab).

Copy-and-paste the following lines three lines of R code into the Console and hit \texttt{\textless{}Enter\textgreater{}}.

\begin{verbatim}
install.packages("gitcreds")
library(gitcreds)
gitcreds_set()
\end{verbatim}

Note that in the \emph{Console} you can use Ctrl+v to paste instead of Ctrl+Shift+v (or just Cmd+v on a Mac).

You will be prompted to enter the token that you just created above on GitHub.com. You should copy-and-paste the token from where you saved it to prevent any spelling errors, and then press \texttt{\textless{}Enter\textgreater{}} again.

Now you should be all set up!

\hypertarget{installing-and-updating-r-packages-on-rstudio-server}{%
\section{Installing and updating R packages on RStudio Server}\label{installing-and-updating-r-packages-on-rstudio-server}}

There are two ways to install and update the packages on RStudio Server. We will learn both the techniques in this tutorial.

\hypertarget{option---1-without-commands}{%
\subsection{Option - 1 (Without commands)}\label{option---1-without-commands}}

This is the easiest option to install and update the packages on RStudio Server. You can find a list of all the installed packages on RStudio Server by clicking the Packages tab (present in the lower right window) and then to install any package click on the Install button.

\begin{center}\includegraphics[width=1\linewidth]{img/packages_step_1} \end{center}

RStudio Server will then open a new window to insert the package name which you need to install. After entering package name click on the Install button.

\begin{center}\includegraphics[width=1\linewidth]{img/packages_step_2} \end{center}

After clicking the Install button, RStudio Server will install the package, and you will be able to see the newly installed package in the list.

\begin{center}\includegraphics[width=1\linewidth]{img/packages_step_3} \end{center}

To import any package click on the checkbox of the package. RStudio Server will automatically import the package which you have selected. Similarly to update packages you need to click on the update tab, and RStudio Server will give you a list of packages which are outdated and ask your permission to update.

\begin{center}\includegraphics[width=1\linewidth]{img/packages_step_4} \end{center}

\hypertarget{option---2-with-commands}{%
\subsection{Option - 2 (With commands)}\label{option---2-with-commands}}

You can also install and update packages by typing commands in RStudio Server Console. To install any package on RStudio Server, you need to use \textbf{install.packages(``PackageName'')} command in R. Example of installing ``ROCR'' package is shown below. The package which you need to install will get replaced by ``ROCR''. Also, after installing any package, the list also gets updated. (R also installs the dependent packages if needed when you install any package).

\begin{center}\includegraphics[width=1\linewidth]{img/packages_step_5} \end{center}

To import any package in RStudio Server, you need to use \textbf{library(PacakageName)} command. Below an example of importing ``ROCR'' package is shown. In R, many times package gets imported along with its dependent packages.

To update all the outdated packages \textbf{update.packages(ask = FALSE)} command is used. If you do not include \textbf{ask = False} then RStudio Server will ask your permission every time while updating the package.

\begin{center}\includegraphics[width=1\linewidth]{img/packages_step_6} \end{center}

\hypertarget{interacting-with-your-files-on-rstudio-server}{%
\section{Interacting with your files on RStudio Server}\label{interacting-with-your-files-on-rstudio-server}}

In RStudio Server it is easy to interact with your files. We can easily upload, delete and rename the files from the menu which is present in the lower right window.

\begin{center}\includegraphics[width=1\linewidth]{img/interacting_step_1} \end{center}

\hypertarget{setting-path-for-the-working-directory}{%
\subsection{Setting path for the working directory}\label{setting-path-for-the-working-directory}}

Before starting interacting with files, it is essential to set the path of the working directory. This can be done by selecting More option and then click on Set As Working Directory. So whenever you upload or save any file that file will get stored in your working directory. Also, if you are in the different folder and you want to go in the working directory folder, then you can click on Go To Working Directory option.

\begin{center}\includegraphics[width=1\linewidth]{img/interacting_step_5} \end{center}

\hypertarget{creating-a-folder}{%
\subsection{Creating a folder}\label{creating-a-folder}}

If you want to create a new folder, then click on New Folder option. It will ask you for the name which you would like to give to that folder and then press on Ok.

\begin{center}\includegraphics[width=1\linewidth]{img/interacting_step_2} \end{center}

\hypertarget{uploading-a-file}{%
\subsection{Uploading a file}\label{uploading-a-file}}

If you want to upload any file, then click on Upload option and then upload a file from your local drive to your account on RStudio Server. Please note that you can only upload one file at a time. If you want to upload multiple files, then please create a .zip file and then upload.

\begin{center}\includegraphics[width=1\linewidth]{img/interacting_step_3} \end{center}

\hypertarget{deleting-or-renaming-a-file}{%
\subsection{Deleting or renaming a file}\label{deleting-or-renaming-a-file}}

You can also delete or rename the file easily by clicking the options which are present in the lower right window. Before removing or renaming the file, it is mandatory to click the checkbox of the file which you would like to process.

\begin{center}\includegraphics[width=1\linewidth]{img/interacting_step_4} \end{center}

\hypertarget{viewing-a-file}{%
\subsection{Viewing a file}\label{viewing-a-file}}

First, you need to go to a folder in which the file is present. You can quickly switch from one folder to another folder by clicking on the path present in the lower right window (Home icon). To view a file, click on a file which you would like to see or edit and the file will open in the upper right window.

\begin{center}\includegraphics[width=1\linewidth]{img/interacting_step_6} \end{center}

\hypertarget{creating-a-new-file-on-rstudio-server}{%
\section{Creating a new file on RStudio Server}\label{creating-a-new-file-on-rstudio-server}}

To create a new file in RStudio Server, you need to click on File tab. In file tab click on New File and then you will see different formats of the file which you can create in RStudio Server. Select the appropriate file type, and then you will get a blank file which will open in the upper left window.

\begin{center}\includegraphics[width=1\linewidth]{img/file_step_1} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{img/file_step_2} \end{center}

\hypertarget{using-rstudio-server-to-clone-a-github-repo-as-a-new-project}{%
\section{Using RStudio Server to clone a Github Repo as a new project}\label{using-rstudio-server-to-clone-a-github-repo-as-a-new-project}}

\hypertarget{step---1}{%
\subsection{Step - 1}\label{step---1}}

Log in to your RStudio Server account on \url{https://rstudio.cos.gmu.edu/}.

\begin{center}\includegraphics[width=1\linewidth]{img/clone_step_1} \end{center}

\hypertarget{step---2}{%
\subsection{Step - 2}\label{step---2}}

In this tutorial, we will be creating a new project in RStudio Server to clone a GitHub repository. To create a new project click on the right side (cube containing R icon) button on RStudo Server screen. After clicking the button, you will see a menu and then click on ``New Project\ldots{}''.

\begin{center}\includegraphics[width=1\linewidth]{img/clone_step_2} \end{center}

\hypertarget{step---3}{%
\subsection{Step - 3}\label{step---3}}

A new window will open and select ``Version Control'' option from the window.

\begin{center}\includegraphics[width=1\linewidth]{img/clone_step_3} \end{center}

\hypertarget{step---4}{%
\subsection{Step - 4}\label{step---4}}

Now, select ``Git'' option from the menu.

\begin{center}\includegraphics[width=1\linewidth]{img/clone_step_4} \end{center}

\hypertarget{step---5}{%
\subsection{Step - 5}\label{step---5}}

In this step, you need to go to your GitHub account (\url{https://github.com}) and copy the URL of the repository which you need to clone. In this tutorial ``test'' repository will be used. (Please remember to copy the URL of the repository which you need to clone)

\begin{center}\includegraphics[width=1\linewidth]{img/clone_step_5} \end{center}

\hypertarget{step---6}{%
\subsection{Step - 6}\label{step---6}}

In the last step, you have copied the URL from GitHub. Now, paste the URL in ``Repository URL'' textbox. RStudio Server will automatically use the same repository name from the URL and then click on ``Create Project'' button.

\begin{center}\includegraphics[width=1\linewidth]{img/clone_step_6} \end{center}

\hypertarget{step---7}{%
\subsection{Step - 7}\label{step---7}}

You have successfully cloned a repository from GitHub in RStudio Server. After creating a project, you will be in the newly cloned repository. You can easily access the files from the repository in the lower right window. Also, if you want to verify the repository, then you can check it on right side (cube containing R icon) button in the RStudio Server.

\begin{center}\includegraphics[width=1\linewidth]{img/clone_step_7} \end{center}

\hypertarget{how-to-stage-commit-and-push-to-github-using-rstudio-server}{%
\section{How to stage, commit, and push to Github using RStudio Server}\label{how-to-stage-commit-and-push-to-github-using-rstudio-server}}

\hypertarget{step---1-1}{%
\subsection{Step - 1}\label{step---1-1}}

Click on the ``Git'' which is present in the upper right window. After clicking the Git button, you will see a list of all files that have been changed since the last commit.

\begin{center}\includegraphics[width=1\linewidth]{img/stage_step_3} \end{center}

\hypertarget{step---2-1}{%
\subsection{Step - 2}\label{step---2-1}}

Click on the ``Staged'' checkbox to stage files which you want to push to GitHub and click on the ``Commit''.

\begin{center}\includegraphics[width=1\linewidth]{img/stage_step_4} \end{center}

\hypertarget{step---3-1}{%
\subsection{Step - 3}\label{step---3-1}}

A new window will open, and it will reflect you the files which you want to commit to GitHub repository. You can also write a commit message in the ``Commit message'' textbox and then click the ``Commit'' button. (DO NOT check the box which says ``Amend previous commit'' - this will only lead to disaster).

\begin{center}\includegraphics[width=1\linewidth]{img/stage_step_5} \end{center}

You will see the following screen after clicking on the ``Commit'' button. Close the window by clicking the ``Close'' button.

\begin{center}\includegraphics[width=1\linewidth]{img/stage_step_6} \end{center}

\hypertarget{step---4-1}{%
\subsection{Step - 4}\label{step---4-1}}

After committing the files on GitHub, you will find the upper right window empty. It means that you have committed the files to the repository. Now, in the final step, you need to click on ``Push'' to push the files in the repository.

\begin{center}\includegraphics[width=1\linewidth]{img/stage_step_7} \end{center}

\hypertarget{step---5-1}{%
\subsection{Step - 5}\label{step---5-1}}

If you have correctly set-up a GitHub PAT (instructions here), then the Push should run normally.

If there is a problem, one of these things may have happened:

\begin{itemize}
\item
  If RStudio asks you for a GitHub username or password, or if you get an error about authentication (e.g.~``Support for password authentication was removed\ldots{}'') then you have probably not followed all of those set-up steps correctly to create a Personal Access Token for GitHub and store it in RStudio: \url{https://book.cds101.com/initial-set-up.html}
\item
  If you get an error about ``merge conflicts'' then you have somehow ended up with conflicting versions of the file in RStudio and on GitHub (this can happen if you manually uploaded a file to GitHub, or if you opened the project in multiple sessions of RStudio simultaneously). If you are not sure how to fix these merge conflicts, then you should contact an instructor for help.
\item
  If you get an error about ``unrelated histories'', then you accidentally checked the ``Ammend previous commit'' box in Step 3 above. You will need to create a new version of the project in GitHub and
\end{itemize}

In the end, you will see a new window containing Git Push message. If everything is correct, then there will not be any errors, and your files have been successfully pushed in GitHub repository.

\begin{center}\includegraphics[width=1\linewidth]{img/stage_step_9} \end{center}

\hypertarget{step---6-1}{%
\subsection{Step - 6}\label{step---6-1}}

You can also crosscheck on GitHub by accessing the specific repository.

\begin{center}\includegraphics[width=1\linewidth]{img/stage_step_10} \end{center}

In this way, you can easily stage, commit and push to GitHub using RStudio Server. If you have any questions or concerns, then please contact your advisor.

\hypertarget{switching-between-github-repos-in-rstudio-server}{%
\section{Switching between Github repos in RStudio Server}\label{switching-between-github-repos-in-rstudio-server}}

In the last tutorial, we learned how to clone a repository from GitHub to RStudio Server. Now, we will see how to switch from one repository to another in RStudio Server.

\hypertarget{step---1-2}{%
\subsection{Step - 1}\label{step---1-2}}

Log in to your RStudio Server account on \url{https://rstudio.cos.gmu.edu/}. You can see your current repository on the right side (cube containing R icon) button on RStudo Server screen. Currently, I am working in the ``rstudio-server-tutorial'' repository, and there are two other repositories which I have already cloned from GitHub (``test'' and ``github-tutorial'').

To switch from one repository to another click on the right side (cube containing R icon) button and then click on the repository which you want to access. In this case, I want to move from ``rstudio-server-tutorial'' repository to ``test'' repository. (While performing tutorial, please note that you will have different repositories)

\begin{center}\includegraphics[width=1\linewidth]{img/switch_step_1} \end{center}

\hypertarget{step---2-2}{%
\subsection{Step - 2}\label{step---2-2}}

After clicking on the name of the repository, RStudio Server will switch to the respective repository. You can verify the repository by checking its name on the right side button.

\begin{center}\includegraphics[width=1\linewidth]{img/switch_step_2} \end{center}

In this way, you can quickly switch from one repository to another in RStudio Server. If a particular repository is not available in RStudio Server then first you need to clone that repository from GitHub, and then you can use that repository in RStudio Server.

\hypertarget{other-common-questions-about-rstudio-server}{%
\section{Other common questions about RStudio Server}\label{other-common-questions-about-rstudio-server}}

\hypertarget{what-happens-if-you-close-the-browser-tab}{%
\subsection{What happens if you close the browser tab?}\label{what-happens-if-you-close-the-browser-tab}}

RStudio Server can be accessed via web browser after authenticating the user. If you are working in RStudio Server and mistakenly close the browser, then it will not affect your computations or saved files. You will see the same screen which you have closed after starting the RStudio Server again.

\hypertarget{i-clicked-import-dataset-but-i-cant-find-the-file-i-downloaded-where-is-it}{%
\subsection{I clicked ``import dataset,'' but I can't find the file I downloaded, where is it?}\label{i-clicked-import-dataset-but-i-cant-find-the-file-i-downloaded-where-is-it}}

RStudio Server stores data and code files on the cloud. Whenever you will upload any new file/data or save your code in RStudio Server, then it will store those files in the cloud and not on your local drive.

Also, please note that after uploading files you will be making changes in the files which are uploaded to the cloud. Similarly, if you are using any data set in RStudio Server, then you will be using that from the cloud.

If you would like to have a copy of your work on your local drive, then download that by selecting the ``More'' tab (lower right window) and then click on ``Export\ldots{}''

\begin{center}\includegraphics[width=1\linewidth]{img/question_step_1} \end{center}

\hypertarget{part-r-programming}{%
\part{R Programming}\label{part-r-programming}}

\hypertarget{overview}{%
\chapter{Overview}\label{overview}}

The following chapters will introduce you to the basics of the R programming language.

\hypertarget{r-basics}{%
\chapter{R basics}\label{r-basics}}

You should complete this chapter within the first week of class. We will be using these concepts in every assignment for the rest of the semester, so it is important to become familiar with them.

As you work through the sections of this chapter you should answer the accompanying questions on Blackboard.

\hypertarget{rbasics-data}{%
\section{Data}\label{rbasics-data}}

The central component of everything we will be doing in R this semester is \textbf{data}. Even non-data science programs revolve around data. At a very basic level, a computer is just a fancy calculator that takes in numbers and spits out an answer. To a computer, even things like words and pictures are stored internally as numbers.

\hypertarget{rbasics-numbers}{%
\subsection{Numbers}\label{rbasics-numbers}}

R can handle many types of data. For example, one type of data is a number. Let's start by

When you open RStudio, you will notice that the program is divided up into 3 or 4 panes. On the left, you should see a pane called \textbf{Console}. You can type programming language \textbf{expressions} into the Console after the \texttt{\textgreater{}} symbol, hit enter, and the expression will be \textbf{evaluated}.

Try entering a number after the \texttt{\textgreater{}} in the Console (e.g.~2), then Enter, and see what happens.

When you hit enter, the R interpreter reads in the line, evaluates it, and returns the answer. In this case, you entered 2, so the computer thinks ``Hey, it's a 2! Wow, a two! The result of 2 is\ldots{} drum roll, please\ldots{} 2!'' and you get a two.

Cool! But not, I confess, particularly useful. Let's fix that: next we'll add two numbers together. At the prompt, enter two numbers separated by a plus sign, +

\texttt{\textgreater{}\ 2\ +\ 2}

What do you get?

The plus sign, \texttt{+}, is called an \emph{operator}. As you might expect, it is the \emph{addition operator}. There are many other operators in R. Here are a few of the more useful ones. See if you can figure out what they do:

\begin{itemize}
\tightlist
\item
  \texttt{-}
\item
  \texttt{/}
\item
  \texttt{*}
\item
  \texttt{\^{}}
\item
  \texttt{\%\%}
\item
  \texttt{==}
\item
  \texttt{!=}
\item
  \texttt{\textless{}}
\end{itemize}

Enter each of these at the prompt, with a number on each side, and see what you get, e.g.

\texttt{\textgreater{}\ 3\ **\ 2}

or

\texttt{\textgreater{}\ 5\ ==\ 5}

\hypertarget{r-basics-variables}{%
\section{Variables}\label{r-basics-variables}}

There's a problem with just entering numbers at the prompt like we have been doing so far. We type in our nice calculation (which we call an expression in programming jargon):

\begin{verbatim}
> 5 + 6 / 4 * 5
\end{verbatim}

hit enter, and get the following answer

\begin{verbatim}
[1] 12.5
\end{verbatim}

But what if we need this for a subsequent expression? Alas, the answer has disappeared into the ether, because we haven't saved it anywhere.

To save the result of an expression, we can assign it to a variable. In R, we do this using a left-pointing arrow:

\begin{verbatim}
> a <- 5 + 6 / 4 * 5
\end{verbatim}

Try running this line and see what happens.

Hmm! The RStudio console no longer returns the result of the expression. However, take a look in the upper right pane of RStudio. You should see that the R environment now contains a variable a with an associated value of 12.5.

So how do we reuse this variable? Simple: just replace one of the numbers in our expression with the variable, e.g.:

\begin{verbatim}
> a + 10
[1] 22.5
\end{verbatim}

We could even save the result of this expression into a second variable:

\begin{verbatim}
> b <- a + 10
\end{verbatim}

Take a look in the top right tab in RStudio (called \emph{Environment}). You should see that there are two variables, \texttt{a} and \texttt{b}, with values 12.5 and 22.5 respectively. RStudio keeps track of all the variables that have been created, along with their values, and shows them here so that you can keep track of them more easily.

\hypertarget{more-complicated-data}{%
\section{More Complicated Data}\label{more-complicated-data}}

But what's that I hear you saying? ``Dr.~White, can't I use anything other than simple numbers? What about if I want to store a bunch of numbers at once? Do I have to save each one as a its own variable? You said in the first class that computers can do billions of calculations per second! I can't type in a billion variables - I have to get to my Latin class!''

Never fear - there are lots of ways to store data in R. For example, you can store multiple numbers in a data type called a vector:

\begin{verbatim}
> v <- c(1, 2, 3, 4)
\end{verbatim}

This should pop up in the Environment pane of RStudio.

See what we did there? We used the \emph{function} \texttt{c(...)} and put all the data that we wanted in the vector inside the braces (separated by commas). (More on functions soon).

Here's a question for you: can you use the operators from the first section on vectors?

For example, what happens if you do:

\begin{verbatim}
> v2 <- c(5, 6, 7, 8)
> v + v2
\end{verbatim}

What about the other operators? Do they all work on vectors?

What happens if the vectors are different lengths? For example:

\begin{verbatim}
> v + c(9, 10, 11)
\end{verbatim}

Can you apply an operator to a vector and a number? Does it always give you the result that you expect? For example:

\begin{verbatim}
> v + 1
\end{verbatim}

\hypertarget{functions}{%
\section{Functions}\label{functions}}

Perhaps, keen mathematician that you are, you want to calculate the length of the hypotenuse of a triangle. Dredging up memories of early math classes, you will doubtless recall Pythagoras's theorem that the hypotenuse (the long side) of triangle is given by:

Let's say we have a triangle where the shorter sides (a \& b) are 3 and 4 units long. Can you calculate the length of side c in R using just the operators from the first section?

\emph{Hint \#1:} The square root is equal to the 0.5 power of a number: \texttt{4\ \^{}\ 0.5\ =\ 2}

\emph{Hint \#2:} Just like in regular math equations, R will calculate some operators before others. For example it will do all multiplications before any additions. However, just like in regular math, we can change the order of operations by wrapping parts of our calculation in parentheses: \texttt{(...)}

Did you get the answer 5? Fantastic!

What's that? Another complaint? You have to write out this long expression every time you need the hypotenuse of a triangle (no doubt this is a frequent chore in your day-to-day life at Mason)?

Again, there is a solution! R allows us to save pieces of code in variables. Yes, you heard that right: variables don't just have to store data, they can also store code!

These stored, reusable sections of code are called functions.

For example, you could create a function to calculate the sum of two numbers:

\begin{verbatim}
adder <- function(number1, number2) {
    result <- number1 + number2
    return(result)
}
\end{verbatim}

Entering these 4 lines at the console prompt will be slow and error-prone, so let's try something different.

Click on the ``File'' menu at the top of RStudio. Select ``New File'' and then ``R Script''. A blank editor window should appear in a new pane above the console.

Copy the adder function from the previous page into this empty script. Then press ``Control + Alt + R'' on your keyboard (simultaneously). This will run the contents of your script all at once.

If successful, you should see that \texttt{adder} appears in the Environment pane under a new section called \emph{Functions}.

How do we use our adder function? Go back to the console, and type something like this:

\begin{quote}
adder(3, 5)
\end{quote}

If your function is working correctly you should get the result of the 2 numbers that you entered inside the braces.

Let's take another look at the adder function to understand what's going on:

\begin{verbatim}
adder <- function(number1, number2) {
    result <- number1 + number2
    return(result)
}
\end{verbatim}

\textbf{Line 1:} The first line creates a new function with the \texttt{function} keyword and saves it to the name \texttt{adder} using the assignment operator \texttt{\textless{}-}, just as we did for variables.

After \texttt{function} are a pair of parentheses. Inside these, we put a list of the parameters that the function can take, separated by commas. In this case, our adder function has two paramters (the numbers to add together). We are going to give these numbers the temporary names \texttt{number1} and \texttt{number2} (creative, I know). We will use these parameter names inside the function to refer to these two numbers.

We end the line with an opening curly bracket \texttt{\{} to indicate that the code that follows is part of the function.

\textbf{Line 2:} This is the meat of our adder function. We add our two number paramters together and store them in a variable called \texttt{result}. Its important to note that \texttt{result} only exists inside the curly brackets of the adder function (i.e.~it vanishes after the function has finished).

\textbf{Line 3:} Here we specify what the function is should return: in this case we want to return the \texttt{result} variable.

\textbf{Line 4:} We signal the end of the function with a closing curly bracket (matching the one from the end of line 1).

You might object (and not without reason) that our \texttt{adder} function is a very trivial example. Wouldn't it just be easier to use the \texttt{+} operator?

Yes, it would! So let's make a more complicated function. Can you convert your Pythagorean code from earlier into a function?

\emph{Hint \#3:} The general format of an R function is:

\begin{verbatim}
function_name <- function(argument1, argument2, argument3, ...etc.) {
    some code
    some more code
    …etc.
    return(something)
}
\end{verbatim}

\emph{Hint \#4:} Use an R function like this:

\begin{verbatim}
> function_name(variable1, 104, ...etc.)
\end{verbatim}

i.e.~the function name followed by parentheses containing a comma separated list of data and variables. Using a function is referred to as ``calling a function''.

\hypertarget{part-readings}{%
\part{Readings}\label{part-readings}}

\hypertarget{describing-numerical-data}{%
\chapter{Describing numerical data}\label{describing-numerical-data}}

Many of the figures that we will be creating and analyzing during the course will be representations of univariate (meaning one variable) and bivariate (meaning two variables) data.
You will frequently be asked to write a description about a visualization, and you should aim to be precise and consistent in your terms.
Use the short summaries below as a guide and a reminder when writing about the features contained in a univariate or bivariate plot.

{Describing univariate data}

When describing the visual properties of univariate data, remember to discuss the following traits:

\begin{itemize}
\item
  shape:

  \begin{itemize}
  \item
    right-skewed, left-skewed, symmetric (skew is to the side of the longer tail)
  \item
    unimodal, bimodal, multimodal, uniform
  \end{itemize}
\item
  center: mean (\texttt{mean}), median (\texttt{median}), mode (not always useful)
\item
  spread: range (\texttt{range}), standard deviation (\texttt{sd}), inter-quartile range (\texttt{IQR})
\item
  unusual observations
\end{itemize}

For additional guidance, follow this link for a summary of what the above terms mean: \url{http://stattrek.com/statistics/charts/data-patterns.aspx}

{Describing bivariate data}

When describing the visual properties of univariate data, you will frequently be looking at a scatterplot.
When describing the shapes of scatterplots we highlight:

\begin{itemize}
\item
  \textbf{Direction}: What direction is the data trending?
  Positive direction or negative direction?
\item
  \textbf{Form}: This is analogous to \emph{shape} for univariate data.
  Is the dataset linear?
  Is is curved?
  Does it not have a form?
\item
  \textbf{Strength}: How clustered are the data points around the underlying form?
  Stated another way, what are the strength of the correlations?
  Typical descriptors are \emph{strong}, \emph{moderate}, or \emph{weak}.
\end{itemize}

\hypertarget{representing-distributions}{%
\chapter{Representing distributions}\label{representing-distributions}}

This chapter introduces us to two more ways we can represent univariate (single variable) data distributions as we start to learn how to compare two or more distributions and draw conclusions.
So far we've focused on representing univariate distributions using frequency histograms (by default, \texttt{geom\_histogram()} sorts data into different bins and tells you how many end up in each one).
Frequency histograms are useful for examining the particulars of a single variable, but have limited utility when directly comparing distributions that contain different numbers of observations.
We resolve this issue by introducing the normalized version of the frequency histogram, the \textbf{probability mass function} (PMF).
As we'll see, the PMF still has its limitations, which will motivate us to consider other, more robust representations of data distributions, such as the very useful \textbf{cumulative distribution function} (CDF).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Packages}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(readr)}
\CommentTok{\# Dataset}
\NormalTok{county\_complete }\OtherTok{\textless{}{-}} \FunctionTok{read\_rds}\NormalTok{(}\AttributeTok{path =} \StringTok{"data/county\_complete.rds"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{probability-mass-functions}{%
\section{Probability mass functions}\label{probability-mass-functions}}

\hypertarget{example-dataset}{%
\subsection{Example dataset}\label{example-dataset}}

We use an example dataset of the average time it takes for people to commute to work across 3143 counties in the United States (collected between 2006-2010) to help illustrate the meaning and uses of the probability mass function.
The frequency histogram for these times can be plotted using the following code snippet:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{county\_complete }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\AttributeTok{mapping =} \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ mean\_work\_travel)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{binwidth =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=1\linewidth]{distributions_files/figure-latex/mean-travel-time-freq-hist-1} \end{center}

\hypertarget{pmfs}{%
\subsection{PMFs}\label{pmfs}}

The \textbf{probability mass function} (PMF) represents a distribution by sorting the data into bins (much like the frequency histogram) and then associates a probability with each bin in the distribution.
A \textbf{probability} is a frequency expressed as a fraction of the sample size \emph{n}.
Therefore we can directly convert a frequency histogram to a PMF by dividing the count in each bin by the sample size \emph{n}.
This process is called \textbf{normalization}.

As an example, consider the following short sample,

\begin{verbatim}
1  2  2  3  5
\end{verbatim}

If we choose a binwidth of 1, then we get a frequency histogram that looks like this:

\begin{center}\includegraphics[width=1\linewidth]{distributions_files/figure-latex/simple-freq-hist-1} \end{center}

There are 5 observations in this sample.
So, we can convert to a PMF by dividing the count within each bin by 5, getting a histogram that looks like this:

\begin{center}\includegraphics[width=1\linewidth]{distributions_files/figure-latex/simple-pmf-hist-1} \end{center}

The relative shape stays the same, but compare the values along the vertical axis between the two figures.
You'll find that they are no longer integers and are instead probabilities.
The normalization procedure (dividing by 5) guarantees that adding together the probabilities of all bins will equal 1.
For this example, we find that the probability of drawing the number 1 is 0.2, drawing 2 is 0.4, drawing 3 is 0.2, drawing 4 is 0, and drawing 5 is 0.2.
That is the biggest difference between a frequency histogram and a PMF, the frequency histogram maps from values to integer counters, while the PMF maps from values to fractional probabilities.

\hypertarget{plotting-pmfs}{%
\subsection{Plotting PMFs}\label{plotting-pmfs}}

The syntax for plotting a PMF using {ggplot2} is nearly identical to what you would use to create a frequency histogram.
The one modification is that you need to include \texttt{y\ =\ ..density..} inside \texttt{aes()}.
As a simple example, let's take the full distribution of the average work travel times from earlier and plot it as a PMF:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{county\_complete }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\AttributeTok{mapping =} \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ mean\_work\_travel, }\AttributeTok{y =}\NormalTok{ ..density..)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{binwidth =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=1\linewidth]{distributions_files/figure-latex/mean-travel-time-pmf-1} \end{center}

Let's do a comparison to show how one might use a PMF for analysis.
For example, we could ask if two midwestern states such as Nebraska and Iowa have the same distribution of work travel times, or if there is a meaningful difference between the two.
First, let's filter the dataset to only include these two states:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nebraska\_iowa }\OtherTok{\textless{}{-}}\NormalTok{ county\_complete }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(state }\SpecialCharTok{==} \StringTok{"Iowa"} \SpecialCharTok{|}\NormalTok{ state }\SpecialCharTok{==} \StringTok{"Nebraska"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Now let's plot the frequency histogram:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nebraska\_iowa }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}
    \AttributeTok{mapping =} \FunctionTok{aes}\NormalTok{(}
      \AttributeTok{x =}\NormalTok{ mean\_work\_travel,}
      \AttributeTok{fill =}\NormalTok{ state,}
      \AttributeTok{color =}\NormalTok{ state}
\NormalTok{    ),}
    \AttributeTok{position =} \StringTok{"identity"}\NormalTok{,}
    \AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{,}
    \AttributeTok{binwidth =} \DecValTok{1}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=1\linewidth]{distributions_files/figure-latex/ia-ne-travel-times-freq-hist-1} \end{center}

The \texttt{position\ =\ "identity"} input overlaps the two distributions (instead of stacking them) and \texttt{alpha\ =\ 0.5} makes the distributions translucent, so that you can see both despite the overlap.
On our first glance, it looks like the center of the Nebraska times is lower than the center of the Iowa times, and that both have a long tail on the right-hand side.
However, if we do a count summary,

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nebraska\_iowa }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{(state)}
\end{Highlighting}
\end{Shaded}

\begin{table}
\centering
\begin{tabular}{l|r}
\hline
state & n\\
\hline
Iowa & 99\\
\hline
Nebraska & 93\\
\hline
\end{tabular}
\end{table}

we find that the two states do not have the exact same number of counties, although they are close in this particular example.
Nonetheless, any comparisons should be done using a PMF in order to account for differences in the sample size.
We use the following code to create a PMF plot:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nebraska\_iowa }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}
    \AttributeTok{mapping =} \FunctionTok{aes}\NormalTok{(}
      \AttributeTok{x =}\NormalTok{ mean\_work\_travel,}
      \AttributeTok{y =}\NormalTok{ ..density..,}
      \AttributeTok{fill =}\NormalTok{ state,}
      \AttributeTok{color =}\NormalTok{ state}
\NormalTok{    ),}
    \AttributeTok{position =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{binwidth =} \DecValTok{1}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=1\linewidth]{distributions_files/figure-latex/ia-ne-travel-times-pmf-1} \end{center}

The trend that the center of the travel times in Nebraska is slightly smaller than in Iowa continues to hold even after converting to a PMF.

To provide an example where a PMF is clearly necessary, what if we compare New Jersey with Virginia?
Virginia has many more counties than New Jersey:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{county\_complete }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(state }\SpecialCharTok{==} \StringTok{"New Jersey"} \SpecialCharTok{|}\NormalTok{ state }\SpecialCharTok{==} \StringTok{"Virginia"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{(state)}
\end{Highlighting}
\end{Shaded}

\begin{table}
\centering
\begin{tabular}{l|r}
\hline
state & n\\
\hline
New Jersey & 21\\
\hline
Virginia & 134\\
\hline
\end{tabular}
\end{table}

As a result, comparing their frequency histograms gives you this:

\begin{center}\includegraphics[width=1\linewidth]{distributions_files/figure-latex/va-nj-travel-times-freq-hist-1} \end{center}

The New Jersey distribution is dwarfed by the Virginia distribution and it makes it difficult to make comparisons.
However, if we instead compare PMFs, we get this:

\begin{center}\includegraphics[width=1\linewidth]{distributions_files/figure-latex/va-nj-travel-times-pmf-1} \end{center}

So, for example, we can now make statements like ``a randomly selected resident in New Jersey is twice as likely as a randomly chosen resident in Virginia to have an average work travel time of 30 minutes.''
The PMF allows for an ``apples-to-apples'' comparison of the average travel times.

\hypertarget{cumulative-distribution-functions}{%
\section{Cumulative distribution functions}\label{cumulative-distribution-functions}}

\hypertarget{the-limits-of-probability-mass-functions}{%
\subsection{The limits of probability mass functions}\label{the-limits-of-probability-mass-functions}}

Probability mass functions (PMFs) work well if the number of unique values is small.
But as the number of unique values increases, the probability associated with each value gets smaller and the effect of random noise increases.

Let's recall that, in the previous reading, we plotted and compared PMFs of the average work travel time in Virginia and New Jersey, which resulted in this figure:

\begin{center}\includegraphics[width=1\linewidth]{distributions_files/figure-latex/va-nj-travel-times-pmf-1} \end{center}

What happens if we choose \texttt{binwidth\ =\ 0.1} for plotting the \texttt{mean\_work\_travel} distribution?
The values in \texttt{mean\_work\_travel} are reported to the first decimal place, so \texttt{binwidth\ =\ 0.1} does not ``smooth out'' the data.
This increases the number of distinct values in \texttt{mean\_work\_travel} from 41 to 304.
The comparison between the Virginia and New Jersey PMFs will then look like this:

\begin{center}\includegraphics[width=1\linewidth]{distributions_files/figure-latex/mean-work-travel-pmf-no-rounding-1} \end{center}

This visualization has a lot of spikes of similar heights, which makes this difficult to interpret and limits its usefulness.
Also, it can be hard to see overall patterns; for example, what is the approximate difference in means between these two distributions?

This illustrates the tradeoff when using histograms and PMFs for visualizing single variables.
If we smooth things out by using larger bin sizes, then we can lose information that may be useful.
On the other hand, using small bin sizes creates plots like the one above, which is of limited (if any) utility.

An alternative that avoids these problems is the cumulative distribution function (CDF), which we turn to describing next.
But before we discuss CDFs, we first have to understand the concept of percentiles.

\hypertarget{percentiles}{%
\subsection{Percentiles}\label{percentiles}}

If you have taken a standardized test, you probably got your results in the form of a raw score and a \textbf{percentile rank}.
In this context, the percentile rank is the fraction of people who scored lower than you (or the same).
So if you are ``in the 90th percentile'', you did as well as or better than 90\% of the people who took the exam.

As an example, say that you and 4 other people took a test and received the following scores:

\begin{verbatim}
55  66  77  88  99
\end{verbatim}

If you received the score of 88, then what is your percentile rank?
We can calculate it as follows:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{test\_scores }\OtherTok{\textless{}{-}} \FunctionTok{data\_frame}\NormalTok{(}\AttributeTok{score =} \FunctionTok{combine}\NormalTok{(}\DecValTok{55}\NormalTok{, }\DecValTok{66}\NormalTok{, }\DecValTok{77}\NormalTok{, }\DecValTok{88}\NormalTok{, }\DecValTok{99}\NormalTok{))}
  
\NormalTok{number\_of\_tests }\OtherTok{\textless{}{-}}\NormalTok{ test\_scores }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pull}\NormalTok{(n)}
  
\NormalTok{number\_of\_lower\_scores }\OtherTok{\textless{}{-}}\NormalTok{ test\_scores }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(score }\SpecialCharTok{\textless{}=} \DecValTok{88}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pull}\NormalTok{(n)}
  
\NormalTok{percentile\_rank }\OtherTok{\textless{}{-}} \FloatTok{100.0} \SpecialCharTok{*}\NormalTok{ number\_of\_lower\_scores }\SpecialCharTok{/}\NormalTok{ number\_of\_tests}
\end{Highlighting}
\end{Shaded}

From this, we find that the percentile rank for a score of 88 is 80.
Mathematically, the calculation is \(100 \times \dfrac{4}{5} = 80\).

As you can see, if you are given a value, it is easy to find its percentile rank; going the other way is slightly harder.
One way to do this is to sort the scores and find the row number that corresponds to a percentile rank.
To find the row number, divide the total number of scores by 100, multiply that number by the desired percentile rank, and then \emph{round up} to the nearest integer value.
The rounding up operation can be handled via the \texttt{ceiling()} function.
So, for our example, the value with percentile rank 55 is:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{percentile\_rank\_row\_number }\OtherTok{\textless{}{-}} \FunctionTok{ceiling}\NormalTok{(}\DecValTok{55} \SpecialCharTok{*}\NormalTok{ number\_of\_tests }\SpecialCharTok{/} \DecValTok{100}\NormalTok{)}

\NormalTok{test\_scores }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(score) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{slice}\NormalTok{(percentile\_rank\_row\_number)}
\end{Highlighting}
\end{Shaded}

\begin{table}
\centering
\begin{tabular}{r}
\hline
score\\
\hline
77\\
\hline
\end{tabular}
\end{table}

The result of this calculation is called a \textbf{percentile}.
So this means that, in the distribution of exam scores, the 55th percentile corresponds to a score of 77.

In R, there is a function called \texttt{quantile()} that can do the above calculation automatically, although you need to take care with the inputs.
Let's first show what happens when we aren't careful.
We might think that we can calculate the 55th percentile by running:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{test\_scores }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pull}\NormalTok{(score) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{quantile}\NormalTok{(}\AttributeTok{probs =} \FunctionTok{combine}\NormalTok{(}\FloatTok{0.55}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{table}
\centering
\begin{tabular}{l|r}
\hline
  & x\\
\hline
55\% & 79.2\\
\hline
\end{tabular}
\end{table}

We get a score of 79.2, which isn't in our dataset.
This happens because \texttt{quantile()} interpolates between the scores by default.
Sometimes you will want this behavior, other times you will not.
When the dataset is this small, it doesn't make as much sense to permit interpolation, as it can be based on rather aggressive assumptions about what intermediate scores might look like.
To tell \texttt{quantile()} to compute scores in the same manner as we did above, add the input \texttt{type\ =\ 1}:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{test\_scores }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pull}\NormalTok{(score) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{quantile}\NormalTok{(}\AttributeTok{probs =} \FunctionTok{combine}\NormalTok{(}\FloatTok{0.55}\NormalTok{), }\AttributeTok{type =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}
\centering
\begin{tabular}{l|r}
\hline
  & x\\
\hline
55\% & 77\\
\hline
\end{tabular}
\end{table}

This, as expected, agrees with the manual calculation.

It is worth emphasizing that the difference between ``percentile'' and ``percentile rank'' can be confusing, and people do not always use the terms precisely.
To summarize, if we want to know the percentage of people obtained scores equal to or lower than ours, then we are computing a percentile rank.
If we start with a percentile, then we are computing the score in the distribution that corresponds with it.

\hypertarget{cdfs}{%
\subsection{CDFs}\label{cdfs}}

Now that we understand percentiles and percentile ranks, we are ready to tackle the \textbf{cumulative distribution function} (CDF).
The CDF is the function that maps from a value to its percentile rank.
To find the CDF for any particular value in our distribution, we compute the fraction of values in the distribution less than or equal to our selected value.
Computing this is similar to how we calculated the percentile rank, except that the result is a probability in the range 0 -- 1 rather than a percentile rank in the range 0 -- 100.
For our test scores example, we can manually compute the CDF in the following way:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{test\_scores\_cdf }\OtherTok{\textless{}{-}}\NormalTok{ test\_scores }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(score) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{cdf =} \FunctionTok{row\_number}\NormalTok{() }\SpecialCharTok{/} \FunctionTok{n}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\begin{table}
\centering
\begin{tabular}{r|r}
\hline
score & cdf\\
\hline
55 & 0.2\\
\hline
66 & 0.4\\
\hline
77 & 0.6\\
\hline
88 & 0.8\\
\hline
99 & 1.0\\
\hline
\end{tabular}
\end{table}

The visualization of the CDF looks like:

\begin{center}\includegraphics[width=1\linewidth]{distributions_files/figure-latex/test-scores-cdf-plot-1} \end{center}

As you can see, the CDF of a sample looks like a sequence of steps.
Appropriately enough, this is called a step function, and the CDF of \emph{any} sample is a step function.

Also note that we can evaluate the CDF for any value, not just values that appear in the sample.
If we select a value that is less than the smallest value in the sample, then the CDF is 0.
If we select a value that is greater than the largest value, then the CDF is 1.

\hypertarget{representing-cdfs}{%
\subsection{Representing CDFs}\label{representing-cdfs}}

While it's good to know how to manually compute the CDF, we can construct the CDF of a sample automatically using the \texttt{geom\_step()} function if we include \texttt{stat\ =\ "ecdf"} as an additional input.
Let's use this to look at the CDF for the average work travel time for the full dataset:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{county\_complete }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_step}\NormalTok{(}\AttributeTok{mapping =} \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ mean\_work\_travel), }\AttributeTok{stat =} \StringTok{"ecdf"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{y =} \StringTok{"CDF"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=1\linewidth]{distributions_files/figure-latex/mean-work-travel-cdf-visualization-1} \end{center}

With this plot we can easily specify an average work travel time percentile and read the associated time from the plot and vice-versa.

\hypertarget{comparing-cdfs}{%
\subsection{Comparing CDFs}\label{comparing-cdfs}}

CDFs are especially useful for comparing distributions.
Let's revisit the comparison we made between the average work travel times in Nebraska and Iowa.
Here is the full code that converts those distributions into CDFs:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{county\_complete }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(state }\SpecialCharTok{==} \StringTok{"Nebraska"} \SpecialCharTok{|}\NormalTok{ state }\SpecialCharTok{==} \StringTok{"Iowa"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_step}\NormalTok{(}
    \AttributeTok{mapping =} \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ mean\_work\_travel, }\AttributeTok{color =}\NormalTok{ state),}
    \AttributeTok{stat =} \StringTok{"ecdf"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{y =} \StringTok{"CDF"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=1\linewidth]{distributions_files/figure-latex/compare-cdf-of-ne-ia-travel-times-plot-1} \end{center}

This visualization makes the shapes of the distributions and the relative differences between them much clearer.
We see that Nebraska has shorter average work travel times for most of the distribution, at least until you reach an average time of 25 minutes, after which the Nebraska and Iowa distributions become similar to one another.

While it takes some time to get used to CDFs, it is worth the effort to do so as they show more information, more clearly, than PMFs.

\hypertarget{credits}{%
\section{Credits}\label{credits}}

This chapter, ``Representing distributions,'' is a derivative of ``Chapter 3 Probability mass functions'' and ``Chapter 4 Cumulative distribution functions'' in \href{http://a.co/grOJGrv}{Allen B. Downey, \emph{Think Stats: Exploratory Data Analysis}, 2nd ed.~(O'Reilly Media, Sebastopol, CA, 2014)}, used under \href{http://creativecommons.org/licenses/by-nc-sa/4.0/}{CC BY-NC-SA 4.0}.

\hypertarget{statistical-inference-with-infer}{%
\chapter{Statistical inference with infer}\label{statistical-inference-with-infer}}

\hypertarget{case-study-comparing-work-travel-times}{%
\section{Case study: Comparing work travel times}\label{case-study-comparing-work-travel-times}}

The following is a worked example using the county complete dataset from Section \ref{representing-distributions} that demonstrates how to use the \texttt{infer} package to test if the difference in mean values of two distributions is statistically significant.
To follow along, load the following libraries and dataset into your R session:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Packages}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(readr)}
\FunctionTok{library}\NormalTok{(infer)}
\CommentTok{\# Dataset}
\NormalTok{county\_complete }\OtherTok{\textless{}{-}} \FunctionTok{read\_rds}\NormalTok{(}
  \FunctionTok{url}\NormalTok{(}\StringTok{"http://data.cds101.com/county\_complete.rds"}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{work-travel-times-in-iowa-and-nebraska}{%
\subsection{Work travel times in Iowa and Nebraska}\label{work-travel-times-in-iowa-and-nebraska}}

In Section \ref{representing-distributions}, we looked at the distribution of average work travel times in Iowa and Nebraska measured on the county level.

\begin{center}\includegraphics[width=1\linewidth]{infer_files/figure-latex/ia-ne-travel-times-pmf-1} \end{center}

In our visual inspection of the probability mass function, we concluded that the distribution of work travel times is shifted slightly towards shorter commutes in Nebraska versus Iowa.
The summary statistics for the two distributions seem to support this conclusion:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Filter dataset to only include counties in Iowa and Nebraska}
\NormalTok{ia\_ne\_county }\OtherTok{\textless{}{-}}\NormalTok{ county\_complete }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(state }\SpecialCharTok{==} \StringTok{"Iowa"} \SpecialCharTok{|}\NormalTok{ state }\SpecialCharTok{==} \StringTok{"Nebraska"}\NormalTok{)}

\CommentTok{\# Compute summary statistics of mean\_work\_travel column for Iowa and Nebraska}
\NormalTok{ia\_ne\_summary\_stats }\OtherTok{\textless{}{-}}\NormalTok{ ia\_ne\_county }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(state) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}
    \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(mean\_work\_travel),}
    \AttributeTok{median =} \FunctionTok{median}\NormalTok{(mean\_work\_travel),}
    \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(mean\_work\_travel),}
    \AttributeTok{iqr =} \FunctionTok{IQR}\NormalTok{(mean\_work\_travel)}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{table}
\centering
\begin{tabular}{l|r|r|r|r}
\hline
state & mean & median & sd & iqr\\
\hline
Iowa & 19.11 & 18.5 & 3.425 & 4.4\\
\hline
Nebraska & 17.97 & 17.6 & 3.823 & 5.0\\
\hline
\end{tabular}
\end{table}

Let's compute the difference in means directly using \texttt{ia\_ne\_summary\_stats}.
First, we need to grab the \texttt{mean} column:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ia\_ne\_means }\OtherTok{\textless{}{-}}\NormalTok{ ia\_ne\_summary\_stats }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pull}\NormalTok{(mean)}
\end{Highlighting}
\end{Shaded}

\texttt{ia\_ne\_means} is a simple vector that stores two numbers.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ia\_ne\_means}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 19.11 17.97
\end{verbatim}

The first number of the vector, which we can access with \texttt{ia\_ne\_means{[}1{]}}, is the mean work travel times in Iowa.
The second number of the vector, which we can access with \texttt{ia\_ne\_means{[}2{]}}, is the mean work travel times in Nebraska.
Knowing this, we easily compute the difference in means,

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ia\_ne\_diff\_in\_means }\OtherTok{\textless{}{-}}\NormalTok{ ia\_ne\_means[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{{-}}\NormalTok{ ia\_ne\_means[}\DecValTok{2}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

obtaining the following value of \texttt{ia\_ne\_diff\_in\_means}:

\begin{verbatim}
# (mean work travel time in Iowa) - (mean work travel time in Nebraska)
ia_ne_diff_in_means = 1.15 minutes
\end{verbatim}

However, only checking the numerical difference between the mean values is not enough if we want to claim there is a \textbf{statistically significant} difference in commute times between Iowa and Nebraska.
There is significant overlap between the two distributions, with the standard deviation (sd) of each distribution being 3--4 times \emph{larger} than the difference in means.
Before we can conclude that the difference in means is statistically significant, we need to estimate how likely it is that this difference could have arisen from chance alone.

\hypertarget{defining-the-hypothesis-test}{%
\subsection{Defining the hypothesis test}\label{defining-the-hypothesis-test}}

To determine whether or not there is a meaningful difference in means between the two distributions, we will conduct a two-sided hypothesis test using the following null and alternative hypotheses:

\begin{itemize}
\item
  \textbf{Null hypothesis}: There is no difference between the mean work travel time in Iowa and the mean work travel time in Nebraska.

  \[\text{H}_{0}:\mu_{\text{IA}}-\mu_{\text{NE}}=0\]
\item
  \textbf{Alternative hypothesis}: There is a difference between the mean work travel time in Iowa and the mean work travel time in Nebraska.

  \[\text{H}_{\text{A}}:\mu_{\text{IA}}-\mu_{\text{NE}}\neq{}0\]
\end{itemize}

We set our significance level to \(\alpha=0.05\), which we will use as a cutoff for determining whether or not a result is statistically significant.

\hypertarget{building-the-null-distribution}{%
\subsection{Building the null distribution}\label{building-the-null-distribution}}

To conduct our hypothesis test, we first must generate our null distribution using the \texttt{infer} package:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ia\_ne\_mean\_work\_travel\_null }\OtherTok{\textless{}{-}}\NormalTok{ ia\_ne\_county }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{specify}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ mean\_work\_travel }\SpecialCharTok{\textasciitilde{}}\NormalTok{ state) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{hypothesize}\NormalTok{(}\AttributeTok{null =} \StringTok{"independence"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{generate}\NormalTok{(}\AttributeTok{reps =} \DecValTok{10000}\NormalTok{, }\AttributeTok{type =} \StringTok{"permute"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{calculate}\NormalTok{(}\AttributeTok{stat =} \StringTok{"diff in means"}\NormalTok{, }\AttributeTok{order =} \FunctionTok{combine}\NormalTok{(}\StringTok{"Iowa"}\NormalTok{, }\StringTok{"Nebraska"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Let's explain what each of these lines is doing.
We start by piping our filtered dataset stored in \texttt{ia\_ne\_county} into \texttt{specify}:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{specify}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ mean\_work\_travel }\SpecialCharTok{\textasciitilde{}}\NormalTok{ state)}
\end{Highlighting}
\end{Shaded}

Here we \emph{specify} the \textbf{response} variable and the \textbf{explanatory} variable in the \texttt{formula\ =} input keyword.
The formula syntax is given as follows:

\begin{verbatim}
response ~ explanatory
\end{verbatim}

Therefore, in our formula \texttt{mean\_work\_travel\ \textasciitilde{}\ state}, \texttt{mean\_work\_travel} is the response variable and \texttt{state} is the explanatory variable.
How do we know to use \texttt{mean\_work\_travel} as the response variable?
It's because of how we formulated our null and alternative hypotheses, such that we are testing whether a person's mean work travel time is affected by the state he or she lives in, \textbf{not} whether the state that a person lives in is affected by his or her mean work travel time.
Finally, because the \textbf{response variable} is numerical, we don't use the \texttt{success\ =} keyword in \texttt{specify}.

The next line that we pipe into is:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hypothesize}\NormalTok{(}\AttributeTok{null =} \StringTok{"independence"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Here we indicate that we are conducting a hypothesis test to check whether or not the variables provided in \texttt{specify} are independent of one another.
A basic rule of thumb is, if you specify \textbf{both} an explanatory and a response variable in the formula of \texttt{specify}, then you will use \texttt{null\ =\ "independence"}.

Next we pipe into this line:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{generate}\NormalTok{(}\AttributeTok{reps =} \DecValTok{10000}\NormalTok{, }\AttributeTok{type =} \StringTok{"permute"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Here we indicate that we want to \emph{permute} the \texttt{mean\_work\_travel} and \texttt{state} columns 10,000 times to build up our null distribution.
In effect, we are randomly shuffling the rows in \texttt{mean\_work\_travel} into a different order, and then randomly shuffling the rows in \texttt{state} into yet another order, which should remove any connections between the \texttt{mean\_work\_travel} and \texttt{state} columns (this is what we mean by null distribution).
We know to use \texttt{type\ =\ "permute"} because we have specified both a response and an explanatory variable and we want to see what happens when we assume the two columns are independent.
As for \texttt{reps\ =\ 10000}, this controls the overall accuracy of our hypothesis tests.
There is no hard and fast rule for the value to set, but if you want more accurate results, increase \texttt{reps}.
However, keep in mind that the larger \texttt{reps} is, the \emph{longer} it will take to complete the calculation.

We finish up by piping into the last line:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{calculate}\NormalTok{(}\AttributeTok{stat =} \StringTok{"diff in means"}\NormalTok{, }\AttributeTok{order =} \FunctionTok{combine}\NormalTok{(}\StringTok{"Iowa"}\NormalTok{, }\StringTok{"Nebraska"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Here we indicate that we are comparing the difference in means between our two distributions (the mean work travel times in Iowa and Nebraska).
The input \texttt{order\ =\ combine("Iowa",\ "Nebraska")} defines the subtraction order, so we will find the difference in means by subtracting the mean time in Iowa from the mean time in Nebraska, which is the same order we used for \texttt{ia\_ne\_diff\_in\_means\ \textless{}-\ ia\_ne\_means{[}1{]}\ -\ ia\_ne\_means{[}2{]}}.
As for the \texttt{stat} input, we know to use \texttt{stat\ =\ "diff\ in\ means"} because of how we formulated our null and alternative hypotheses, i.e.~we are comparing the \textbf{difference} in \textbf{mean} work travel times between Iowa and Nebraska.
The way we know that we \textbf{can't} use something like \texttt{stat\ =\ "diff\ in\ props"} is because at least one of our variables in \texttt{specify} is numerical (\texttt{mean\_work\_travel}).
The input \texttt{stat\ =\ "diff\ in\ props"} only applies if \textbf{both} the explanatory and response variables are categorical.

The null distribution that we generated looks as follows:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ia\_ne\_mean\_work\_travel\_null }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{visualize}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{x =} \StringTok{"difference in means"}\NormalTok{,}
    \AttributeTok{title =} \StringTok{"Difference in mean work travel times null distribution"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=1\linewidth]{infer_files/figure-latex/ia-ne-diff-in-means-null-distribution-1} \end{center}

\hypertarget{computing-the-two-sided-p-value}{%
\subsection{Computing the two-sided p-value}\label{computing-the-two-sided-p-value}}

After we've generated our null distribution, we can compute the \emph{p}-value using \texttt{get\_p\_value}.
To compute a \emph{p}-value, we need an \textbf{observed statistic}, which is simply the difference in means we computed using the dataset itself.
This is what we computed using \texttt{ia\_ne\_diff\_in\_means\ \textless{}-\ ia\_ne\_means{[}1{]}\ -\ ia\_ne\_means{[}2{]}}.
However, \texttt{infer} also provides a shortcut for computing the observed statistic so that you don't have to use \texttt{summarize()},

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ia\_ne\_diff\_in\_means }\OtherTok{\textless{}{-}}\NormalTok{ ia\_ne\_county }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{specify}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ mean\_work\_travel }\SpecialCharTok{\textasciitilde{}}\NormalTok{ state) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{calculate}\NormalTok{(}\AttributeTok{stat =} \StringTok{"diff in means"}\NormalTok{, }\AttributeTok{order =} \FunctionTok{combine}\NormalTok{(}\StringTok{"Iowa"}\NormalTok{, }\StringTok{"Nebraska"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Note that all we've done is taken the code we used to generate the null distribution and removed the \texttt{hypothesize()} and \texttt{generate()} lines.
Now that we have our observed statistic, we can compute the \emph{p}-value for our \textbf{two-sided hypothesis test},

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ia\_ne\_p\_value\_two\_sided }\OtherTok{\textless{}{-}}\NormalTok{ ia\_ne\_mean\_work\_travel\_null }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{get\_p\_value}\NormalTok{(}\AttributeTok{obs\_stat =}\NormalTok{ ia\_ne\_diff\_in\_means, }\AttributeTok{direction =} \StringTok{"both"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}
\centering
\begin{tabular}{r}
\hline
p\_value\\
\hline
0.0344\\
\hline
\end{tabular}
\end{table}

Our two-sided p-value is 0.0344, which is below our significance level of \(\alpha=0.05\). We therefore reject the null hypothesis in favor of the alternative hypothesis. The difference between the mean work travel times in Iowa and Nebraska is statistically significant.

We visualize the meaning of the \emph{p}-value in the following way:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ia\_ne\_mean\_work\_travel\_null }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{visualize}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{shade\_p\_value}\NormalTok{(}\AttributeTok{obs\_stat =}\NormalTok{ ia\_ne\_diff\_in\_means, }\AttributeTok{direction =} \StringTok{"both"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{x =} \StringTok{"difference in means"}\NormalTok{,}
    \AttributeTok{title =} \StringTok{"Difference in mean work travel times null distribution"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=1\linewidth]{infer_files/figure-latex/ia-ne-diff-in-means-null-distribution-p-values-1} \end{center}

The portions of the null distribution that are in the shaded red area correspond to results that are \textbf{more extreme} than the observed value 1.15 in a two-sided hypothesis test.
The more that a null distribution lies within the red portions of the visualization, the more likely it becomes that we will fail to reject the null distribution and the difference in means that we observed in the dataset arose due to random chance alone.

\hypertarget{computing-the-95-confidence-interval}{%
\subsection{Computing the 95\% confidence interval}\label{computing-the-95-confidence-interval}}

In addition to the two-sided hypothesis test, it is also good practice to compute the 95\% confidence interval for the difference in mean work travel times between Iowa and Nebraska.
To compute this, we need to generate the \textbf{bootstrap distribution} for the difference in means:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ia\_ne\_mean\_work\_travel\_bootstrap }\OtherTok{\textless{}{-}}\NormalTok{ ia\_ne\_county }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{specify}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ mean\_work\_travel }\SpecialCharTok{\textasciitilde{}}\NormalTok{ state) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{generate}\NormalTok{(}\AttributeTok{reps =} \DecValTok{10000}\NormalTok{, }\AttributeTok{type =} \StringTok{"bootstrap"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{calculate}\NormalTok{(}\AttributeTok{stat =} \StringTok{"diff in means"}\NormalTok{, }\AttributeTok{order =} \FunctionTok{combine}\NormalTok{(}\StringTok{"Iowa"}\NormalTok{, }\StringTok{"Nebraska"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

You'll notice that the code to generate the bootstrap distribution is pretty similar to the code used to generate the null distribution.
All we had to do was remove the \texttt{hypothesize(null\ =\ "independence")} line and change the \texttt{type\ =} keyword in \texttt{generate} from \texttt{"permute"} to \texttt{"bootstrap"}, and that's it!

You might be wondering, how are the methods for generating the null distribution and bootstrap distribution different?
For this example, they differ in two important ways:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Unlike when we generated the null distribution, the \texttt{mean\_work\_travel} and \texttt{state} columns are \textbf{not} randomly shuffled
\item
  Generating a bootstrap distribution requires \emph{sampling with replacement}, meaning we grab different rows in \texttt{ia\_ne\_county} at random (we might even grab the same row more than), which we do not do if we permute the columns
\end{enumerate}

The bootstrap distribution we just generated looks as follows:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ia\_ne\_mean\_work\_travel\_bootstrap }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{visualize}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{x =} \StringTok{"difference in means"}\NormalTok{,}
    \AttributeTok{title =} \StringTok{"Difference in mean work travel times bootstrap distribution"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=1\linewidth]{infer_files/figure-latex/ia-ne-mean-work-travel-bootstrap-visualization-1} \end{center}

This shows what could happen if we went out and collected another set of samples of the data in this dataset.
Due to random variations in the people we survey, sometimes we might end up with a dataset where the difference between the mean work travel times in Iowa and Nebraska is closer to 2 minutes instead of 1 minute, or it might be closer to zero.
Most of the time, it will be close to 1 minute.

The 95\% confidence interval is defined as the fraction of the data in the bootstrap distribution that lies between the 2.5th and 97.5th percentiles:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ia\_ne\_ci95 }\OtherTok{\textless{}{-}}\NormalTok{ ia\_ne\_mean\_work\_travel\_bootstrap }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{get\_confidence\_interval}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{table}
\centering
\begin{tabular}{r|r}
\hline
lower\_ci & upper\_ci\\
\hline
0.1084 & 2.162\\
\hline
\end{tabular}
\end{table}

This means that, if we keep collecting new samples of mean work travel times in Iowa and Nebraska, we expect that 95\% of our samples will have a difference in mean work travel times that lies between 0.108422456770497 and 2.16224274606866.
Also note that the lower bound of the confidence interval does not intersect with a difference of means equal to zero, lending further support to the conclusion we reached using our two-sided hypothesis test.

We close this example by visualizing the 95\% confidence interval by shading the middle 95\% of the data in the bootstrap distribution:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ia\_ne\_mean\_work\_travel\_bootstrap }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{visualize}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{shade\_confidence\_interval}\NormalTok{(}\AttributeTok{endpoints =}\NormalTok{ ia\_ne\_ci95) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{x =} \StringTok{"difference in means"}\NormalTok{,}
    \AttributeTok{title =} \StringTok{"Difference in mean work travel times 95\% confidence interval"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=1\linewidth]{infer_files/figure-latex/ia-ne-mean-work-travel-bootstrap-visualization-ci95-1} \end{center}

  \bibliography{bib/references.bib,bib/packages.bib}

\end{document}
