<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8.1 Case study: Comparing work travel times | Introduction to Computational and Data Sciences</title>
  <meta name="description" content="Supplemental textbook for the CDS 101 course at George Mason University." />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="8.1 Case study: Comparing work travel times | Introduction to Computational and Data Sciences" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Supplemental textbook for the CDS 101 course at George Mason University." />
  <meta name="github-repo" content="mason-cds-intro-comput-sci/intro-cds" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8.1 Case study: Comparing work travel times | Introduction to Computational and Data Sciences" />
  
  <meta name="twitter:description" content="Supplemental textbook for the CDS 101 course at George Mason University." />
  

<meta name="author" content="James K. Glasbrenner" />
<meta name="author" content="Ajay Kulkarni" />
<meta name="author" content="Dominic White" />


<meta name="date" content="2020-03-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="statistical-inference-with-infer.html"/>
<link rel="next" href="references-1.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="https://fonts.googleapis.com/css?family=Fira+Mono:400,500,700|IBM+Plex+Serif:400,400i,500,500i|Montserrat:400,400i,500,500i,700,700i|Roboto:400,400i,500,500i&amp;subset=latin-ext" rel="stylesheet">


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to Computational and Data Sciences</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Frontmatter</a><ul>
<li class="chapter" data-level="" data-path="r-session-information.html"><a href="r-session-information.html"><i class="fa fa-check"></i>R session information</a></li>
</ul></li>
<li class="part"><span><b>I Toolbox</b></span></li>
<li class="chapter" data-level="1" data-path="toolbox-introduction.html"><a href="toolbox-introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="github.html"><a href="github.html"><i class="fa fa-check"></i><b>2</b> GitHub</a><ul>
<li class="chapter" data-level="2.1" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>2.1</b> Getting started</a><ul>
<li class="chapter" data-level="2.1.1" data-path="getting-started.html"><a href="getting-started.html#github-signup"><i class="fa fa-check"></i><b>2.1.1</b> Account sign-up</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="navigating-the-github-site.html"><a href="navigating-the-github-site.html"><i class="fa fa-check"></i><b>2.2</b> Navigating the GitHub site</a><ul>
<li class="chapter" data-level="2.2.1" data-path="navigating-the-github-site.html"><a href="navigating-the-github-site.html#github-navigation-main-dashboard"><i class="fa fa-check"></i><b>2.2.1</b> Main dashboard</a></li>
<li class="chapter" data-level="2.2.2" data-path="navigating-the-github-site.html"><a href="navigating-the-github-site.html#profile-page"><i class="fa fa-check"></i><b>2.2.2</b> Profile page</a></li>
<li class="chapter" data-level="2.2.3" data-path="navigating-the-github-site.html"><a href="navigating-the-github-site.html#settings"><i class="fa fa-check"></i><b>2.2.3</b> Settings</a></li>
<li class="chapter" data-level="2.2.4" data-path="navigating-the-github-site.html"><a href="navigating-the-github-site.html#class-organization-page"><i class="fa fa-check"></i><b>2.2.4</b> Class organization page</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="repositories.html"><a href="repositories.html"><i class="fa fa-check"></i><b>2.3</b> Repositories</a></li>
<li class="chapter" data-level="2.4" data-path="additional-topics.html"><a href="additional-topics.html"><i class="fa fa-check"></i><b>2.4</b> Additional topics</a><ul>
<li class="chapter" data-level="2.4.1" data-path="additional-topics.html"><a href="additional-topics.html#how-to-create-a-repository"><i class="fa fa-check"></i><b>2.4.1</b> How to create a repository</a></li>
<li class="chapter" data-level="2.4.2" data-path="additional-topics.html"><a href="additional-topics.html#how-to-import-a-repository"><i class="fa fa-check"></i><b>2.4.2</b> How to import a repository</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="rstudio-server.html"><a href="rstudio-server.html"><i class="fa fa-check"></i><b>3</b> RStudio Server</a><ul>
<li class="chapter" data-level="3.1" data-path="big-picture-overview-of-rstudio-server.html"><a href="big-picture-overview-of-rstudio-server.html"><i class="fa fa-check"></i><b>3.1</b> Big picture overview of RStudio Server</a><ul>
<li class="chapter" data-level="3.1.1" data-path="big-picture-overview-of-rstudio-server.html"><a href="big-picture-overview-of-rstudio-server.html#rstudio"><i class="fa fa-check"></i><b>3.1.1</b> RStudio</a></li>
<li class="chapter" data-level="3.1.2" data-path="big-picture-overview-of-rstudio-server.html"><a href="big-picture-overview-of-rstudio-server.html#rstudio-server-1"><i class="fa fa-check"></i><b>3.1.2</b> RStudio Server</a></li>
<li class="chapter" data-level="3.1.3" data-path="big-picture-overview-of-rstudio-server.html"><a href="big-picture-overview-of-rstudio-server.html#reference"><i class="fa fa-check"></i><b>3.1.3</b> Reference</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="a-guided-tour-of-rstudio-servers-default-interface.html"><a href="a-guided-tour-of-rstudio-servers-default-interface.html"><i class="fa fa-check"></i><b>3.2</b> A guided tour of RStudio Server’s default interface</a><ul>
<li class="chapter" data-level="3.2.1" data-path="a-guided-tour-of-rstudio-servers-default-interface.html"><a href="a-guided-tour-of-rstudio-servers-default-interface.html#rstudio-server-sub-windows"><i class="fa fa-check"></i><b>3.2.1</b> RStudio Server sub-windows</a></li>
<li class="chapter" data-level="3.2.2" data-path="a-guided-tour-of-rstudio-servers-default-interface.html"><a href="a-guided-tour-of-rstudio-servers-default-interface.html#file-tab"><i class="fa fa-check"></i><b>3.2.2</b> File tab</a></li>
<li class="chapter" data-level="3.2.3" data-path="a-guided-tour-of-rstudio-servers-default-interface.html"><a href="a-guided-tour-of-rstudio-servers-default-interface.html#edit-tab"><i class="fa fa-check"></i><b>3.2.3</b> Edit tab</a></li>
<li class="chapter" data-level="3.2.4" data-path="a-guided-tour-of-rstudio-servers-default-interface.html"><a href="a-guided-tour-of-rstudio-servers-default-interface.html#code-tab"><i class="fa fa-check"></i><b>3.2.4</b> Code tab</a></li>
<li class="chapter" data-level="3.2.5" data-path="a-guided-tour-of-rstudio-servers-default-interface.html"><a href="a-guided-tour-of-rstudio-servers-default-interface.html#view-tab"><i class="fa fa-check"></i><b>3.2.5</b> View tab</a></li>
<li class="chapter" data-level="3.2.6" data-path="a-guided-tour-of-rstudio-servers-default-interface.html"><a href="a-guided-tour-of-rstudio-servers-default-interface.html#plots-tab"><i class="fa fa-check"></i><b>3.2.6</b> Plots tab</a></li>
<li class="chapter" data-level="3.2.7" data-path="a-guided-tour-of-rstudio-servers-default-interface.html"><a href="a-guided-tour-of-rstudio-servers-default-interface.html#session-tab"><i class="fa fa-check"></i><b>3.2.7</b> Session tab</a></li>
<li class="chapter" data-level="3.2.8" data-path="a-guided-tour-of-rstudio-servers-default-interface.html"><a href="a-guided-tour-of-rstudio-servers-default-interface.html#build-tab"><i class="fa fa-check"></i><b>3.2.8</b> Build tab</a></li>
<li class="chapter" data-level="3.2.9" data-path="a-guided-tour-of-rstudio-servers-default-interface.html"><a href="a-guided-tour-of-rstudio-servers-default-interface.html#debug-tab"><i class="fa fa-check"></i><b>3.2.9</b> Debug tab</a></li>
<li class="chapter" data-level="3.2.10" data-path="a-guided-tour-of-rstudio-servers-default-interface.html"><a href="a-guided-tour-of-rstudio-servers-default-interface.html#proflie-tab"><i class="fa fa-check"></i><b>3.2.10</b> Proflie tab</a></li>
<li class="chapter" data-level="3.2.11" data-path="a-guided-tour-of-rstudio-servers-default-interface.html"><a href="a-guided-tour-of-rstudio-servers-default-interface.html#tools-tab"><i class="fa fa-check"></i><b>3.2.11</b> Tools tab</a></li>
<li class="chapter" data-level="3.2.12" data-path="a-guided-tour-of-rstudio-servers-default-interface.html"><a href="a-guided-tour-of-rstudio-servers-default-interface.html#help-tab"><i class="fa fa-check"></i><b>3.2.12</b> Help tab</a></li>
<li class="chapter" data-level="3.2.13" data-path="a-guided-tour-of-rstudio-servers-default-interface.html"><a href="a-guided-tour-of-rstudio-servers-default-interface.html#references"><i class="fa fa-check"></i><b>3.2.13</b> References</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="help-and-documentation-for-r-and-rstudio-server.html"><a href="help-and-documentation-for-r-and-rstudio-server.html"><i class="fa fa-check"></i><b>3.3</b> Help and documentation for R and RStudio Server</a></li>
<li class="chapter" data-level="3.4" data-path="initial-set-up.html"><a href="initial-set-up.html"><i class="fa fa-check"></i><b>3.4</b> Initial Set-up</a><ul>
<li class="chapter" data-level="3.4.1" data-path="initial-set-up.html"><a href="initial-set-up.html#install-required-packages"><i class="fa fa-check"></i><b>3.4.1</b> Install required packages</a></li>
<li class="chapter" data-level="3.4.2" data-path="initial-set-up.html"><a href="initial-set-up.html#change-global-options"><i class="fa fa-check"></i><b>3.4.2</b> Change Global Options</a></li>
<li class="chapter" data-level="3.4.3" data-path="initial-set-up.html"><a href="initial-set-up.html#configure-rstudio-for-use-with-git"><i class="fa fa-check"></i><b>3.4.3</b> Configure RStudio for use with Git</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="installing-and-updating-r-packages-on-rstudio-server.html"><a href="installing-and-updating-r-packages-on-rstudio-server.html"><i class="fa fa-check"></i><b>3.5</b> Installing and updating R packages on RStudio Server</a><ul>
<li class="chapter" data-level="3.5.1" data-path="installing-and-updating-r-packages-on-rstudio-server.html"><a href="installing-and-updating-r-packages-on-rstudio-server.html#option---1-without-commands"><i class="fa fa-check"></i><b>3.5.1</b> Option - 1 (Without commands)</a></li>
<li class="chapter" data-level="3.5.2" data-path="installing-and-updating-r-packages-on-rstudio-server.html"><a href="installing-and-updating-r-packages-on-rstudio-server.html#option---2-with-commands"><i class="fa fa-check"></i><b>3.5.2</b> Option - 2 (With commands)</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="interacting-with-your-files-on-rstudio-server.html"><a href="interacting-with-your-files-on-rstudio-server.html"><i class="fa fa-check"></i><b>3.6</b> Interacting with your files on RStudio Server</a><ul>
<li class="chapter" data-level="3.6.1" data-path="interacting-with-your-files-on-rstudio-server.html"><a href="interacting-with-your-files-on-rstudio-server.html#setting-path-for-the-working-directory"><i class="fa fa-check"></i><b>3.6.1</b> Setting path for the working directory</a></li>
<li class="chapter" data-level="3.6.2" data-path="interacting-with-your-files-on-rstudio-server.html"><a href="interacting-with-your-files-on-rstudio-server.html#creating-a-folder"><i class="fa fa-check"></i><b>3.6.2</b> Creating a folder</a></li>
<li class="chapter" data-level="3.6.3" data-path="interacting-with-your-files-on-rstudio-server.html"><a href="interacting-with-your-files-on-rstudio-server.html#uploading-a-file"><i class="fa fa-check"></i><b>3.6.3</b> Uploading a file</a></li>
<li class="chapter" data-level="3.6.4" data-path="interacting-with-your-files-on-rstudio-server.html"><a href="interacting-with-your-files-on-rstudio-server.html#deleting-or-renaming-a-file"><i class="fa fa-check"></i><b>3.6.4</b> Deleting or renaming a file</a></li>
<li class="chapter" data-level="3.6.5" data-path="interacting-with-your-files-on-rstudio-server.html"><a href="interacting-with-your-files-on-rstudio-server.html#viewing-a-file"><i class="fa fa-check"></i><b>3.6.5</b> Viewing a file</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="creating-a-new-file-on-rstudio-server.html"><a href="creating-a-new-file-on-rstudio-server.html"><i class="fa fa-check"></i><b>3.7</b> Creating a new file on RStudio Server</a></li>
<li class="chapter" data-level="3.8" data-path="using-rstudio-server-to-clone-a-github-repo-as-a-new-project.html"><a href="using-rstudio-server-to-clone-a-github-repo-as-a-new-project.html"><i class="fa fa-check"></i><b>3.8</b> Using RStudio Server to clone a Github Repo as a new project</a><ul>
<li class="chapter" data-level="3.8.1" data-path="using-rstudio-server-to-clone-a-github-repo-as-a-new-project.html"><a href="using-rstudio-server-to-clone-a-github-repo-as-a-new-project.html#step---1"><i class="fa fa-check"></i><b>3.8.1</b> Step - 1</a></li>
<li class="chapter" data-level="3.8.2" data-path="using-rstudio-server-to-clone-a-github-repo-as-a-new-project.html"><a href="using-rstudio-server-to-clone-a-github-repo-as-a-new-project.html#step---2"><i class="fa fa-check"></i><b>3.8.2</b> Step - 2</a></li>
<li class="chapter" data-level="3.8.3" data-path="using-rstudio-server-to-clone-a-github-repo-as-a-new-project.html"><a href="using-rstudio-server-to-clone-a-github-repo-as-a-new-project.html#step---3"><i class="fa fa-check"></i><b>3.8.3</b> Step - 3</a></li>
<li class="chapter" data-level="3.8.4" data-path="using-rstudio-server-to-clone-a-github-repo-as-a-new-project.html"><a href="using-rstudio-server-to-clone-a-github-repo-as-a-new-project.html#step---4"><i class="fa fa-check"></i><b>3.8.4</b> Step - 4</a></li>
<li class="chapter" data-level="3.8.5" data-path="using-rstudio-server-to-clone-a-github-repo-as-a-new-project.html"><a href="using-rstudio-server-to-clone-a-github-repo-as-a-new-project.html#step---5"><i class="fa fa-check"></i><b>3.8.5</b> Step - 5</a></li>
<li class="chapter" data-level="3.8.6" data-path="using-rstudio-server-to-clone-a-github-repo-as-a-new-project.html"><a href="using-rstudio-server-to-clone-a-github-repo-as-a-new-project.html#step---6"><i class="fa fa-check"></i><b>3.8.6</b> Step - 6</a></li>
<li class="chapter" data-level="3.8.7" data-path="using-rstudio-server-to-clone-a-github-repo-as-a-new-project.html"><a href="using-rstudio-server-to-clone-a-github-repo-as-a-new-project.html#step---7"><i class="fa fa-check"></i><b>3.8.7</b> Step - 7</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="how-to-stage-commit-and-push-to-github-using-rstudio-server.html"><a href="how-to-stage-commit-and-push-to-github-using-rstudio-server.html"><i class="fa fa-check"></i><b>3.9</b> How to stage, commit, and push to Github using RStudio Server</a><ul>
<li class="chapter" data-level="3.9.1" data-path="how-to-stage-commit-and-push-to-github-using-rstudio-server.html"><a href="how-to-stage-commit-and-push-to-github-using-rstudio-server.html#step---1-1"><i class="fa fa-check"></i><b>3.9.1</b> Step - 1</a></li>
<li class="chapter" data-level="3.9.2" data-path="how-to-stage-commit-and-push-to-github-using-rstudio-server.html"><a href="how-to-stage-commit-and-push-to-github-using-rstudio-server.html#step---2-1"><i class="fa fa-check"></i><b>3.9.2</b> Step - 2</a></li>
<li class="chapter" data-level="3.9.3" data-path="how-to-stage-commit-and-push-to-github-using-rstudio-server.html"><a href="how-to-stage-commit-and-push-to-github-using-rstudio-server.html#step---3-1"><i class="fa fa-check"></i><b>3.9.3</b> Step - 3</a></li>
<li class="chapter" data-level="3.9.4" data-path="how-to-stage-commit-and-push-to-github-using-rstudio-server.html"><a href="how-to-stage-commit-and-push-to-github-using-rstudio-server.html#step---4-1"><i class="fa fa-check"></i><b>3.9.4</b> Step - 4</a></li>
<li class="chapter" data-level="3.9.5" data-path="how-to-stage-commit-and-push-to-github-using-rstudio-server.html"><a href="how-to-stage-commit-and-push-to-github-using-rstudio-server.html#step---5-1"><i class="fa fa-check"></i><b>3.9.5</b> Step - 5</a></li>
<li class="chapter" data-level="3.9.6" data-path="how-to-stage-commit-and-push-to-github-using-rstudio-server.html"><a href="how-to-stage-commit-and-push-to-github-using-rstudio-server.html#step---6-1"><i class="fa fa-check"></i><b>3.9.6</b> Step - 6</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="switching-between-github-repos-in-rstudio-server.html"><a href="switching-between-github-repos-in-rstudio-server.html"><i class="fa fa-check"></i><b>3.10</b> Switching between Github repos in RStudio Server</a><ul>
<li class="chapter" data-level="3.10.1" data-path="switching-between-github-repos-in-rstudio-server.html"><a href="switching-between-github-repos-in-rstudio-server.html#step---1-2"><i class="fa fa-check"></i><b>3.10.1</b> Step - 1</a></li>
<li class="chapter" data-level="3.10.2" data-path="switching-between-github-repos-in-rstudio-server.html"><a href="switching-between-github-repos-in-rstudio-server.html#step---2-2"><i class="fa fa-check"></i><b>3.10.2</b> Step - 2</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="other-common-questions-about-rstudio-server.html"><a href="other-common-questions-about-rstudio-server.html"><i class="fa fa-check"></i><b>3.11</b> Other common questions about RStudio Server</a><ul>
<li class="chapter" data-level="3.11.1" data-path="other-common-questions-about-rstudio-server.html"><a href="other-common-questions-about-rstudio-server.html#what-happens-if-you-close-the-browser-tab"><i class="fa fa-check"></i><b>3.11.1</b> What happens if you close the browser tab?</a></li>
<li class="chapter" data-level="3.11.2" data-path="other-common-questions-about-rstudio-server.html"><a href="other-common-questions-about-rstudio-server.html#i-clicked-import-dataset-but-i-cant-find-the-file-i-downloaded-where-is-it"><i class="fa fa-check"></i><b>3.11.2</b> I clicked “import dataset,” but I can’t find the file I downloaded, where is it?</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II R Programming</b></span></li>
<li class="chapter" data-level="4" data-path="overview.html"><a href="overview.html"><i class="fa fa-check"></i><b>4</b> Overview</a></li>
<li class="chapter" data-level="5" data-path="r-basics.html"><a href="r-basics.html"><i class="fa fa-check"></i><b>5</b> R basics</a><ul>
<li class="chapter" data-level="5.1" data-path="rbasics-data.html"><a href="rbasics-data.html"><i class="fa fa-check"></i><b>5.1</b> Data</a><ul>
<li class="chapter" data-level="5.1.1" data-path="rbasics-data.html"><a href="rbasics-data.html#rbasics-numbers"><i class="fa fa-check"></i><b>5.1.1</b> Numbers</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="variables-r-basics-variables.html"><a href="variables-r-basics-variables.html"><i class="fa fa-check"></i><b>5.2</b> Variables {r-basics-variables}</a></li>
<li class="chapter" data-level="5.3" data-path="more-complicated-data.html"><a href="more-complicated-data.html"><i class="fa fa-check"></i><b>5.3</b> More Complicated Data</a></li>
<li class="chapter" data-level="5.4" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>5.4</b> Functions</a></li>
</ul></li>
<li class="part"><span><b>III Readings</b></span></li>
<li class="chapter" data-level="6" data-path="describing-numerical-data.html"><a href="describing-numerical-data.html"><i class="fa fa-check"></i><b>6</b> Describing numerical data</a></li>
<li class="chapter" data-level="7" data-path="representing-distributions.html"><a href="representing-distributions.html"><i class="fa fa-check"></i><b>7</b> Representing distributions</a><ul>
<li class="chapter" data-level="7.1" data-path="probability-mass-functions.html"><a href="probability-mass-functions.html"><i class="fa fa-check"></i><b>7.1</b> Probability mass functions</a><ul>
<li class="chapter" data-level="7.1.1" data-path="probability-mass-functions.html"><a href="probability-mass-functions.html#example-dataset"><i class="fa fa-check"></i><b>7.1.1</b> Example dataset</a></li>
<li class="chapter" data-level="7.1.2" data-path="probability-mass-functions.html"><a href="probability-mass-functions.html#pmfs"><i class="fa fa-check"></i><b>7.1.2</b> PMFs</a></li>
<li class="chapter" data-level="7.1.3" data-path="probability-mass-functions.html"><a href="probability-mass-functions.html#plotting-pmfs"><i class="fa fa-check"></i><b>7.1.3</b> Plotting PMFs</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="cumulative-distribution-functions.html"><a href="cumulative-distribution-functions.html"><i class="fa fa-check"></i><b>7.2</b> Cumulative distribution functions</a><ul>
<li class="chapter" data-level="7.2.1" data-path="cumulative-distribution-functions.html"><a href="cumulative-distribution-functions.html#the-limits-of-probability-mass-functions"><i class="fa fa-check"></i><b>7.2.1</b> The limits of probability mass functions</a></li>
<li class="chapter" data-level="7.2.2" data-path="cumulative-distribution-functions.html"><a href="cumulative-distribution-functions.html#percentiles"><i class="fa fa-check"></i><b>7.2.2</b> Percentiles</a></li>
<li class="chapter" data-level="7.2.3" data-path="cumulative-distribution-functions.html"><a href="cumulative-distribution-functions.html#cdfs"><i class="fa fa-check"></i><b>7.2.3</b> CDFs</a></li>
<li class="chapter" data-level="7.2.4" data-path="cumulative-distribution-functions.html"><a href="cumulative-distribution-functions.html#representing-cdfs"><i class="fa fa-check"></i><b>7.2.4</b> Representing CDFs</a></li>
<li class="chapter" data-level="7.2.5" data-path="cumulative-distribution-functions.html"><a href="cumulative-distribution-functions.html#comparing-cdfs"><i class="fa fa-check"></i><b>7.2.5</b> Comparing CDFs</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="credits.html"><a href="credits.html"><i class="fa fa-check"></i><b>7.3</b> Credits</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="statistical-inference-with-infer.html"><a href="statistical-inference-with-infer.html"><i class="fa fa-check"></i><b>8</b> Statistical inference with infer</a><ul>
<li class="chapter" data-level="8.1" data-path="case-study-comparing-work-travel-times.html"><a href="case-study-comparing-work-travel-times.html"><i class="fa fa-check"></i><b>8.1</b> Case study: Comparing work travel times</a><ul>
<li class="chapter" data-level="8.1.1" data-path="case-study-comparing-work-travel-times.html"><a href="case-study-comparing-work-travel-times.html#work-travel-times-in-iowa-and-nebraska"><i class="fa fa-check"></i><b>8.1.1</b> Work travel times in Iowa and Nebraska</a></li>
<li class="chapter" data-level="8.1.2" data-path="case-study-comparing-work-travel-times.html"><a href="case-study-comparing-work-travel-times.html#defining-the-hypothesis-test"><i class="fa fa-check"></i><b>8.1.2</b> Defining the hypothesis test</a></li>
<li class="chapter" data-level="8.1.3" data-path="case-study-comparing-work-travel-times.html"><a href="case-study-comparing-work-travel-times.html#building-the-null-distribution"><i class="fa fa-check"></i><b>8.1.3</b> Building the null distribution</a></li>
<li class="chapter" data-level="8.1.4" data-path="case-study-comparing-work-travel-times.html"><a href="case-study-comparing-work-travel-times.html#computing-the-two-sided-p-value"><i class="fa fa-check"></i><b>8.1.4</b> Computing the two-sided p-value</a></li>
<li class="chapter" data-level="8.1.5" data-path="case-study-comparing-work-travel-times.html"><a href="case-study-comparing-work-travel-times.html#computing-the-95-confidence-interval"><i class="fa fa-check"></i><b>8.1.5</b> Computing the 95% confidence interval</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references-1.html"><a href="references-1.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Computational and Data Sciences</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="case-study-comparing-work-travel-times" class="section level2">
<h2><span class="header-section-number">8.1</span> Case study: Comparing work travel times</h2>
<p>The following is a worked example using the county complete dataset from Section <a href="representing-distributions.html#representing-distributions">7</a> that demonstrates how to use the <code>infer</code> package to test if the difference in mean values of two distributions is statistically significant.
To follow along, load the following libraries and dataset into your R session:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" data-line-number="1"><span class="co"># Packages</span></a>
<a class="sourceLine" id="cb32-2" data-line-number="2"><span class="kw">library</span>(dplyr)</a>
<a class="sourceLine" id="cb32-3" data-line-number="3"><span class="kw">library</span>(ggplot2)</a>
<a class="sourceLine" id="cb32-4" data-line-number="4"><span class="kw">library</span>(readr)</a>
<a class="sourceLine" id="cb32-5" data-line-number="5"><span class="kw">library</span>(infer)</a>
<a class="sourceLine" id="cb32-6" data-line-number="6"><span class="co"># Dataset</span></a>
<a class="sourceLine" id="cb32-7" data-line-number="7">county_complete &lt;-<span class="st"> </span><span class="kw">read_rds</span>(</a>
<a class="sourceLine" id="cb32-8" data-line-number="8">  <span class="kw">url</span>(<span class="st">&quot;http://data.cds101.com/county_complete.rds&quot;</span>)</a>
<a class="sourceLine" id="cb32-9" data-line-number="9">)</a></code></pre></div>
<div id="work-travel-times-in-iowa-and-nebraska" class="section level3">
<h3><span class="header-section-number">8.1.1</span> Work travel times in Iowa and Nebraska</h3>
<p>In Section <a href="representing-distributions.html#representing-distributions">7</a>, we looked at the distribution of average work travel times in Iowa and Nebraska measured on the county level.</p>
<p><img src="infer_files/figure-html/ia-ne-travel-times-pmf-1.svg" width="100%" style="display: block; margin: auto;" /></p>
<p>In our visual inspection of the probability mass function, we concluded that the distribution of work travel times is shifted slightly towards shorter commutes in Nebraska versus Iowa.
The summary statistics for the two distributions seem to support this conclusion:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" data-line-number="1"><span class="co"># Filter dataset to only include counties in Iowa and Nebraska</span></a>
<a class="sourceLine" id="cb33-2" data-line-number="2">ia_ne_county &lt;-<span class="st"> </span>county_complete <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb33-3" data-line-number="3"><span class="st">  </span><span class="kw">filter</span>(state <span class="op">==</span><span class="st"> &quot;Iowa&quot;</span> <span class="op">|</span><span class="st"> </span>state <span class="op">==</span><span class="st"> &quot;Nebraska&quot;</span>)</a>
<a class="sourceLine" id="cb33-4" data-line-number="4"></a>
<a class="sourceLine" id="cb33-5" data-line-number="5"><span class="co"># Compute summary statistics of mean_work_travel column for Iowa and Nebraska</span></a>
<a class="sourceLine" id="cb33-6" data-line-number="6">ia_ne_summary_stats &lt;-<span class="st"> </span>ia_ne_county <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb33-7" data-line-number="7"><span class="st">  </span><span class="kw">group_by</span>(state) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb33-8" data-line-number="8"><span class="st">  </span><span class="kw">summarize</span>(</a>
<a class="sourceLine" id="cb33-9" data-line-number="9">    <span class="dt">mean =</span> <span class="kw">mean</span>(mean_work_travel),</a>
<a class="sourceLine" id="cb33-10" data-line-number="10">    <span class="dt">median =</span> <span class="kw">median</span>(mean_work_travel),</a>
<a class="sourceLine" id="cb33-11" data-line-number="11">    <span class="dt">sd =</span> <span class="kw">sd</span>(mean_work_travel),</a>
<a class="sourceLine" id="cb33-12" data-line-number="12">    <span class="dt">iqr =</span> <span class="kw">IQR</span>(mean_work_travel)</a>
<a class="sourceLine" id="cb33-13" data-line-number="13">  )</a></code></pre></div>
<table class="table table-striped table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
state
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
median
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
iqr
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Iowa
</td>
<td style="text-align:right;">
19.11
</td>
<td style="text-align:right;">
18.5
</td>
<td style="text-align:right;">
3.425
</td>
<td style="text-align:right;">
4.4
</td>
</tr>
<tr>
<td style="text-align:left;">
Nebraska
</td>
<td style="text-align:right;">
17.97
</td>
<td style="text-align:right;">
17.6
</td>
<td style="text-align:right;">
3.823
</td>
<td style="text-align:right;">
5.0
</td>
</tr>
</tbody>
</table>
<p>Let’s compute the difference in means directly using <code>ia_ne_summary_stats</code>.
First, we need to grab the <code>mean</code> column:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" data-line-number="1">ia_ne_means &lt;-<span class="st"> </span>ia_ne_summary_stats <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb34-2" data-line-number="2"><span class="st">  </span><span class="kw">pull</span>(mean)</a></code></pre></div>
<p><code>ia_ne_means</code> is a simple vector that stores two numbers.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" data-line-number="1">ia_ne_means</a></code></pre></div>
<pre><code>## [1] 19.11 17.97</code></pre>
<p>The first number of the vector, which we can access with <code>ia_ne_means[1]</code>, is the mean work travel times in Iowa.
The second number of the vector, which we can access with <code>ia_ne_means[2]</code>, is the mean work travel times in Nebraska.
Knowing this, we easily compute the difference in means,</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" data-line-number="1">ia_ne_diff_in_means &lt;-<span class="st"> </span>ia_ne_means[<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span>ia_ne_means[<span class="dv">2</span>]</a></code></pre></div>
<p>obtaining the following value of <code>ia_ne_diff_in_means</code>:</p>
<pre><code># (mean work travel time in Iowa) - (mean work travel time in Nebraska)
ia_ne_diff_in_means = 1.15 minutes</code></pre>
<p>However, only checking the numerical difference between the mean values is not enough if we want to claim there is a <strong>statistically significant</strong> difference in commute times between Iowa and Nebraska.
There is significant overlap between the two distributions, with the standard deviation (sd) of each distribution being 3–4 times <em>larger</em> than the difference in means.
Before we can conclude that the difference in means is statistically significant, we need to estimate how likely it is that this difference could have arisen from chance alone.</p>
</div>
<div id="defining-the-hypothesis-test" class="section level3">
<h3><span class="header-section-number">8.1.2</span> Defining the hypothesis test</h3>
<p>To determine whether or not there is a meaningful difference in means between the two distributions, we will conduct a two-sided hypothesis test using the following null and alternative hypotheses:</p>
<ul>
<li><p><strong>Null hypothesis</strong>: There is no difference between the mean work travel time in Iowa and the mean work travel time in Nebraska.</p>
<p><span class="math display">\[\text{H}_{0}:\mu_{\text{IA}}-\mu_{\text{NE}}=0\]</span></p></li>
<li><p><strong>Alternative hypothesis</strong>: There is a difference between the mean work travel time in Iowa and the mean work travel time in Nebraska.</p>
<p><span class="math display">\[\text{H}_{\text{A}}:\mu_{\text{IA}}-\mu_{\text{NE}}\neq{}0\]</span></p></li>
</ul>
<p>We set our significance level to <span class="math inline">\(\alpha=0.05\)</span>, which we will use as a cutoff for determining whether or not a result is statistically significant.</p>
</div>
<div id="building-the-null-distribution" class="section level3">
<h3><span class="header-section-number">8.1.3</span> Building the null distribution</h3>
<p>To conduct our hypothesis test, we first must generate our null distribution using the <code>infer</code> package:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" data-line-number="1">ia_ne_mean_work_travel_null &lt;-<span class="st"> </span>ia_ne_county <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb39-2" data-line-number="2"><span class="st">  </span><span class="kw">specify</span>(<span class="dt">formula =</span> mean_work_travel <span class="op">~</span><span class="st"> </span>state) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb39-3" data-line-number="3"><span class="st">  </span><span class="kw">hypothesize</span>(<span class="dt">null =</span> <span class="st">&quot;independence&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb39-4" data-line-number="4"><span class="st">  </span><span class="kw">generate</span>(<span class="dt">reps =</span> <span class="dv">10000</span>, <span class="dt">type =</span> <span class="st">&quot;permute&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb39-5" data-line-number="5"><span class="st">  </span><span class="kw">calculate</span>(<span class="dt">stat =</span> <span class="st">&quot;diff in means&quot;</span>, <span class="dt">order =</span> <span class="kw">combine</span>(<span class="st">&quot;Iowa&quot;</span>, <span class="st">&quot;Nebraska&quot;</span>))</a></code></pre></div>
<p>Let’s explain what each of these lines is doing.
We start by piping our filtered dataset stored in <code>ia_ne_county</code> into <code>specify</code>:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" data-line-number="1"><span class="kw">specify</span>(<span class="dt">formula =</span> mean_work_travel <span class="op">~</span><span class="st"> </span>state)</a></code></pre></div>
<p>Here we <em>specify</em> the <strong>response</strong> variable and the <strong>explanatory</strong> variable in the <code>formula =</code> input keyword.
The formula syntax is given as follows:</p>
<pre><code>response ~ explanatory</code></pre>
<p>Therefore, in our formula <code>mean_work_travel ~ state</code>, <code>mean_work_travel</code> is the response variable and <code>state</code> is the explanatory variable.
How do we know to use <code>mean_work_travel</code> as the response variable?
It’s because of how we formulated our null and alternative hypotheses, such that we are testing whether a person’s mean work travel time is affected by the state he or she lives in, <strong>not</strong> whether the state that a person lives in is affected by his or her mean work travel time.
Finally, because the <strong>response variable</strong> is numerical, we don’t use the <code>success =</code> keyword in <code>specify</code>.</p>
<p>The next line that we pipe into is:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" data-line-number="1"><span class="kw">hypothesize</span>(<span class="dt">null =</span> <span class="st">&quot;independence&quot;</span>)</a></code></pre></div>
<p>Here we indicate that we are conducting a hypothesis test to check whether or not the variables provided in <code>specify</code> are independent of one another.
A basic rule of thumb is, if you specify <strong>both</strong> an explanatory and a response variable in the formula of <code>specify</code>, then you will use <code>null = &quot;independence&quot;</code>.</p>
<p>Next we pipe into this line:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" data-line-number="1"><span class="kw">generate</span>(<span class="dt">reps =</span> <span class="dv">10000</span>, <span class="dt">type =</span> <span class="st">&quot;permute&quot;</span>)</a></code></pre></div>
<p>Here we indicate that we want to <em>permute</em> the <code>mean_work_travel</code> and <code>state</code> columns 10,000 times to build up our null distribution.
In effect, we are randomly shuffling the rows in <code>mean_work_travel</code> into a different order, and then randomly shuffling the rows in <code>state</code> into yet another order, which should remove any connections between the <code>mean_work_travel</code> and <code>state</code> columns (this is what we mean by null distribution).
We know to use <code>type = &quot;permute&quot;</code> because we have specified both a response and an explanatory variable and we want to see what happens when we assume the two columns are independent.
As for <code>reps = 10000</code>, this controls the overall accuracy of our hypothesis tests.
There is no hard and fast rule for the value to set, but if you want more accurate results, increase <code>reps</code>.
However, keep in mind that the larger <code>reps</code> is, the <em>longer</em> it will take to complete the calculation.</p>
<p>We finish up by piping into the last line:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" data-line-number="1"><span class="kw">calculate</span>(<span class="dt">stat =</span> <span class="st">&quot;diff in means&quot;</span>, <span class="dt">order =</span> <span class="kw">combine</span>(<span class="st">&quot;Iowa&quot;</span>, <span class="st">&quot;Nebraska&quot;</span>))</a></code></pre></div>
<p>Here we indicate that we are comparing the difference in means between our two distributions (the mean work travel times in Iowa and Nebraska).
The input <code>order = combine(&quot;Iowa&quot;, &quot;Nebraska&quot;)</code> defines the subtraction order, so we will find the difference in means by subtracting the mean time in Iowa from the mean time in Nebraska, which is the same order we used for <code>ia_ne_diff_in_means &lt;- ia_ne_means[1] - ia_ne_means[2]</code>.
As for the <code>stat</code> input, we know to use <code>stat = &quot;diff in means&quot;</code> because of how we formulated our null and alternative hypotheses, i.e. we are comparing the <strong>difference</strong> in <strong>mean</strong> work travel times between Iowa and Nebraska.
The way we know that we <strong>can’t</strong> use something like <code>stat = &quot;diff in props&quot;</code> is because at least one of our variables in <code>specify</code> is numerical (<code>mean_work_travel</code>).
The input <code>stat = &quot;diff in props&quot;</code> only applies if <strong>both</strong> the explanatory and response variables are categorical.</p>
<p>The null distribution that we generated looks as follows:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" data-line-number="1">ia_ne_mean_work_travel_null <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb45-2" data-line-number="2"><span class="st">  </span><span class="kw">visualize</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb45-3" data-line-number="3"><span class="st">  </span><span class="kw">labs</span>(</a>
<a class="sourceLine" id="cb45-4" data-line-number="4">    <span class="dt">x =</span> <span class="st">&quot;difference in means&quot;</span>,</a>
<a class="sourceLine" id="cb45-5" data-line-number="5">    <span class="dt">title =</span> <span class="st">&quot;Difference in mean work travel times null distribution&quot;</span></a>
<a class="sourceLine" id="cb45-6" data-line-number="6">  )</a></code></pre></div>
<p><img src="infer_files/figure-html/ia-ne-diff-in-means-null-distribution-1.svg" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div id="computing-the-two-sided-p-value" class="section level3">
<h3><span class="header-section-number">8.1.4</span> Computing the two-sided p-value</h3>
<p>After we’ve generated our null distribution, we can compute the <em>p</em>-value using <code>get_p_value</code>.
To compute a <em>p</em>-value, we need an <strong>observed statistic</strong>, which is simply the difference in means we computed using the dataset itself.
This is what we computed using <code>ia_ne_diff_in_means &lt;- ia_ne_means[1] - ia_ne_means[2]</code>.
However, <code>infer</code> also provides a shortcut for computing the observed statistic so that you don’t have to use <code>summarize()</code>,</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" data-line-number="1">ia_ne_diff_in_means &lt;-<span class="st"> </span>ia_ne_county <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb46-2" data-line-number="2"><span class="st">  </span><span class="kw">specify</span>(<span class="dt">formula =</span> mean_work_travel <span class="op">~</span><span class="st"> </span>state) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb46-3" data-line-number="3"><span class="st">  </span><span class="kw">calculate</span>(<span class="dt">stat =</span> <span class="st">&quot;diff in means&quot;</span>, <span class="dt">order =</span> <span class="kw">combine</span>(<span class="st">&quot;Iowa&quot;</span>, <span class="st">&quot;Nebraska&quot;</span>))</a></code></pre></div>
<p>Note that all we’ve done is taken the code we used to generate the null distribution and removed the <code>hypothesize()</code> and <code>generate()</code> lines.
Now that we have our observed statistic, we can compute the <em>p</em>-value for our <strong>two-sided hypothesis test</strong>,</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" data-line-number="1">ia_ne_p_value_two_sided &lt;-<span class="st"> </span>ia_ne_mean_work_travel_null <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb47-2" data-line-number="2"><span class="st">  </span><span class="kw">get_p_value</span>(<span class="dt">obs_stat =</span> ia_ne_diff_in_means, <span class="dt">direction =</span> <span class="st">&quot;both&quot;</span>)</a></code></pre></div>
<table class="table table-striped table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
p_value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.029
</td>
</tr>
</tbody>
</table>
<p>Our two-sided p-value is 0.029, which is below our significance level of <span class="math inline">\(\alpha=0.05\)</span>. We therefore reject the null hypothesis in favor of the alternative hypothesis. The difference between the mean work travel times in Iowa and Nebraska is statistically significant.</p>
<p>We visualize the meaning of the <em>p</em>-value in the following way:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" data-line-number="1">ia_ne_mean_work_travel_null <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb48-2" data-line-number="2"><span class="st">  </span><span class="kw">visualize</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb48-3" data-line-number="3"><span class="st">  </span><span class="kw">shade_p_value</span>(<span class="dt">obs_stat =</span> ia_ne_diff_in_means, <span class="dt">direction =</span> <span class="st">&quot;both&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb48-4" data-line-number="4"><span class="st">  </span><span class="kw">labs</span>(</a>
<a class="sourceLine" id="cb48-5" data-line-number="5">    <span class="dt">x =</span> <span class="st">&quot;difference in means&quot;</span>,</a>
<a class="sourceLine" id="cb48-6" data-line-number="6">    <span class="dt">title =</span> <span class="st">&quot;Difference in mean work travel times null distribution&quot;</span></a>
<a class="sourceLine" id="cb48-7" data-line-number="7">  )</a></code></pre></div>
<p><img src="infer_files/figure-html/ia-ne-diff-in-means-null-distribution-p-values-1.svg" width="100%" style="display: block; margin: auto;" /></p>
<p>The portions of the null distribution that are in the shaded red area correspond to results that are <strong>more extreme</strong> than the observed value 1.15 in a two-sided hypothesis test.
The more that a null distribution lies within the red portions of the visualization, the more likely it becomes that we will fail to reject the null distribution and the difference in means that we observed in the dataset arose due to random chance alone.</p>
</div>
<div id="computing-the-95-confidence-interval" class="section level3">
<h3><span class="header-section-number">8.1.5</span> Computing the 95% confidence interval</h3>
<p>In addition to the two-sided hypothesis test, it is also good practice to compute the 95% confidence interval for the difference in mean work travel times between Iowa and Nebraska.
To compute this, we need to generate the <strong>bootstrap distribution</strong> for the difference in means:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" data-line-number="1">ia_ne_mean_work_travel_bootstrap &lt;-<span class="st"> </span>ia_ne_county <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb49-2" data-line-number="2"><span class="st">  </span><span class="kw">specify</span>(<span class="dt">formula =</span> mean_work_travel <span class="op">~</span><span class="st"> </span>state) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb49-3" data-line-number="3"><span class="st">  </span><span class="kw">generate</span>(<span class="dt">reps =</span> <span class="dv">10000</span>, <span class="dt">type =</span> <span class="st">&quot;bootstrap&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb49-4" data-line-number="4"><span class="st">  </span><span class="kw">calculate</span>(<span class="dt">stat =</span> <span class="st">&quot;diff in means&quot;</span>, <span class="dt">order =</span> <span class="kw">combine</span>(<span class="st">&quot;Iowa&quot;</span>, <span class="st">&quot;Nebraska&quot;</span>))</a></code></pre></div>
<p>You’ll notice that the code to generate the bootstrap distribution is pretty similar to the code used to generate the null distribution.
All we had to do was remove the <code>hypothesize(null = &quot;independence&quot;)</code> line and change the <code>type =</code> keyword in <code>generate</code> from <code>&quot;permute&quot;</code> to <code>&quot;bootstrap&quot;</code>, and that’s it!</p>
<p>You might be wondering, how are the methods for generating the null distribution and bootstrap distribution different?
For this example, they differ in two important ways:</p>
<ol style="list-style-type: decimal">
<li><p>Unlike when we generated the null distribution, the <code>mean_work_travel</code> and <code>state</code> columns are <strong>not</strong> randomly shuffled</p></li>
<li><p>Generating a bootstrap distribution requires <em>sampling with replacement</em>, meaning we grab different rows in <code>ia_ne_county</code> at random (we might even grab the same row more than), which we do not do if we permute the columns</p></li>
</ol>
<p>The bootstrap distribution we just generated looks as follows:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" data-line-number="1">ia_ne_mean_work_travel_bootstrap <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb50-2" data-line-number="2"><span class="st">  </span><span class="kw">visualize</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb50-3" data-line-number="3"><span class="st">  </span><span class="kw">labs</span>(</a>
<a class="sourceLine" id="cb50-4" data-line-number="4">    <span class="dt">x =</span> <span class="st">&quot;difference in means&quot;</span>,</a>
<a class="sourceLine" id="cb50-5" data-line-number="5">    <span class="dt">title =</span> <span class="st">&quot;Difference in mean work travel times bootstrap distribution&quot;</span></a>
<a class="sourceLine" id="cb50-6" data-line-number="6">  )</a></code></pre></div>
<p><img src="infer_files/figure-html/ia-ne-mean-work-travel-bootstrap-visualization-1.svg" width="100%" style="display: block; margin: auto;" /></p>
<p>This shows what could happen if we went out and collected another set of samples of the data in this dataset.
Due to random variations in the people we survey, sometimes we might end up with a dataset where the difference between the mean work travel times in Iowa and Nebraska is closer to 2 minutes instead of 1 minute, or it might be closer to zero.
Most of the time, it will be close to 1 minute.</p>
<p>The 95% confidence interval is defined as the fraction of the data in the bootstrap distribution that lies between the 2.5th and 97.5th percentiles:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" data-line-number="1">ia_ne_ci95 &lt;-<span class="st"> </span>ia_ne_mean_work_travel_bootstrap <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb51-2" data-line-number="2"><span class="st">  </span><span class="kw">get_confidence_interval</span>()</a></code></pre></div>
<table class="table table-striped table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
2.5%
</th>
<th style="text-align:right;">
97.5%
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.1167
</td>
<td style="text-align:right;">
2.153
</td>
</tr>
</tbody>
</table>
<p>This means that, if we keep collecting new samples of mean work travel times in Iowa and Nebraska, we expect that 95% of our samples will have a difference in mean work travel times that lies between 0.1167 and 2.1534.
Also note that the lower bound of the confidence interval does not intersect with a difference of means equal to zero, lending further support to the conclusion we reached using our two-sided hypothesis test.</p>
<p>We close this example by visualizing the 95% confidence interval by shading the middle 95% of the data in the bootstrap distribution:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" data-line-number="1">ia_ne_mean_work_travel_bootstrap <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb52-2" data-line-number="2"><span class="st">  </span><span class="kw">visualize</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb52-3" data-line-number="3"><span class="st">  </span><span class="kw">shade_confidence_interval</span>(<span class="dt">endpoints =</span> ia_ne_ci95) <span class="op">+</span></a>
<a class="sourceLine" id="cb52-4" data-line-number="4"><span class="st">  </span><span class="kw">labs</span>(</a>
<a class="sourceLine" id="cb52-5" data-line-number="5">    <span class="dt">x =</span> <span class="st">&quot;difference in means&quot;</span>,</a>
<a class="sourceLine" id="cb52-6" data-line-number="6">    <span class="dt">title =</span> <span class="st">&quot;Difference in mean work travel times 95% confidence interval&quot;</span></a>
<a class="sourceLine" id="cb52-7" data-line-number="7">  )</a></code></pre></div>
<p><img src="infer_files/figure-html/ia-ne-mean-work-travel-bootstrap-visualization-ci95-1.svg" width="100%" style="display: block; margin: auto;" /></p>

</div>
</div>
<!-- </div> -->
<script src="js/custom.js"></script>
            </section>

          </div>
        </div>
      </div>
<a href="statistical-inference-with-infer.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/mason-cds-intro-comput-sci/intro-cds/edit/master/infer.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
