# Slack

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  out.width = "100%"
)
```

## Getting started 

### Creating a Slack account

After submitting a signed FERPA waiver on Blackboard, you will be invited to our Slack workspace via email. Please make sure to register with your *@masonlive.gmu.edu* email address.

* You will not be able to join Slack until your instructor has approved your uploaded FERPA waiver and sent you the invitation email.
* You will use the same Slack workspace for CDS 101 and CDS 102 (if you are registered for both classes). 
  * You must upload a separate FERPA waiver to the Blackboard section for each class.
  * You will receive a single invite to the shared Slack workspace, and each class's instructor will then add you to the appropriate channels for your section.
  
You can access Slack through a web browser, mobile app, or desktop app. Once you have joined, you can customize your account by:

* changing your username (please stick to either your NetID or *FirstName LastName* so that we know who you are!)
* uploading a profile picture. This is not required, but will help us get to know you better over the course of this semester. *However*, if you do change your picture, *this should be a picture of you*, not of a cartoon, political figure, offensive or provocative imagery, etc.

### Slack policies

1. Please be respectful and polite with all communication on Slack.
2. Follow the guidelines for asking questions.
3. Do not post answers or solutions (see our guidelines for helping out other students).

## How to use Slack

Slack is a messaging tool (very similar to Discord, Microsoft Teams, etc.). There will be two main ways that you use Slack to communicate with instructors and other students:

1. Public messages in shared *channels*
2. Private messages to 1 or more recipients using *direct messages*

### Channels

You and other students from the your section (and other sections) will be assigned to shared channels.

Here are some important channels in our Slack workspace and their uses:

* *101-section-001*: This is a private channel for students in CDS 101 Section 001. You will be assigned to similar channel for your section of CDS 101 and/or 102. Your instructor will use it for communicating information relevant to your class only (and you may also use it if you have a reason to communicate with all other students in your section).

Please do not post extensive code (that another student could copy) in the public channels (use a direct message instead).

### Direct messages

You can send a private message to one or more people as a *Direct Message*.

To do this, scroll down to the "Direct Messages" section of the left-hand menu in Slack, and click the + symbol. Then search for the users you want to message.

If you want to include code in a question, please send it in a Direct Message to your instructor and one of the STARS for your section (i.e. use a single DM with 2 recipients so that we are all in the same message thread).

<!-- ### How to ask (good) questions on Slack {#asking-questions} -->

<!-- ... -->

<!-- ### How to aswer questions on Slack {#answering-questions} -->

<!-- ... -->
